In [ ]:
import csv
from scipy import ndimage
from scipy import linalg
import numpy as np
import nibabel as nib
import os
import glob
import pandas as pd
import matplotlib.pyplot as plt
from operator import itemgetter
import pickle

In [ ]:
#Unnecessay for the network
#for testing out if the images are actually loaded  

with open("dataimage_arr.txt", "rb") as fp:   # Unpickling
    b = pickle.load(fp)
with open("datacsv_new_arr.txt", "rb") as fp:   # Unpickling
    c = pickle.load(fp)

import matplotlib.pyplot as plt

print(type(b))
print(b[0][1][:, :, 20])
plt.imshow(b[0][1][:, :, 20])


In [ ]:
#randomly divide the patients (including their sMRI (dataimage) and informations (csv files)) into training set, 
#validation set, and testing set
import random

index = np.array(range(119))
random.seed(40)
random.shuffle(index)

train_index = index[0:84]
val_index = index[84:96]
test_index = index[96:119]


In [3]:
# reopen the sMRIs and their corresponding csv file (both in txt format) from the GPU
with open("dataimage_arr.txt", "rb") as fp:   
            dataimage = pickle.load(fp)
with open("datacsv_new_arr.txt", "rb") as fp:   
            datacsv = pickle.load(fp)
        

In [4]:
#rename csv group into numbers
mci = 0.
ad = 0.
cn = 0.
total_num = 0.
for i in range(datacsv.shape[0]):
    if datacsv[i][1] == '0':
        mci += 1.
    elif datacsv[i][1] == '1':
        ad += 1.
    elif datacsv[i][1] == '2':
        cn += 1.
total_num = mci + ad + cn
print(mci, ad, cn)

56.0 24.0 39.0


In [5]:

#resave training data (the sMRIs and their corresponding csv file (both in txt format)) to the GPU
dataimage_train = [dataimage[j] for j in train_index]
datacsv_train = [datacsv[j] for j in train_index]
with open("dataimage_train.txt", "wb") as fp:
    pickle.dump(dataimage_train, fp)
with open("datacsv_train.txt", "wb") as fp:
    pickle.dump(datacsv_train, fp)

print("finished")

finished


In [6]:
#resave validation data (the sMRIs and their corresponding csv file (both in txt format)) to the GPU
dataimage_val = [dataimage[j] for j in val_index]
datacsv_val = [datacsv[j] for j in val_index]
with open("dataimage_val.txt", "wb") as fp:
    pickle.dump(dataimage_val, fp)
with open("datacsv_val.txt", "wb") as fp:
    pickle.dump(datacsv_val, fp)
print("finished")

finished


In [7]:
#resave testing data (the sMRIs and their corresponding csv file (both in txt format)) to the GPU
dataimage_test = [dataimage[j] for j in test_index]
datacsv_test = [datacsv[j] for j in test_index]
with open("dataimage_test.txt", "wb") as fp:
    pickle.dump(dataimage_test, fp)
with open("datacsv_test.txt", "wb") as fp:
    pickle.dump(datacsv_test, fp)
print("finished")

finished


In [8]:
from torch.utils.data import Dataset, DataLoader

def ToTensor(np_array):
    tensor = torch.from_numpy(np_array)
    tensor = tensor.float()
    return tensor

class ADNI_Dataset(Dataset):
    
    def __init__(self, ptype, transform=None):
        
        if(ptype == 'train'):
            with open("dataimage_train.txt", "rb") as fp:   # Unpickling
                b_train = pickle.load(fp)
            with open("datacsv_train.txt", "rb") as fp:   # Unpickling
                c_train = pickle.load(fp)
            self.csv = c_train
            self.image = b_train
        
        if(ptype == 'val'):
            with open("dataimage_val.txt", "rb") as fp:   # Unpickling
                b_val = pickle.load(fp)
            with open("datacsv_val.txt", "rb") as fp:   # Unpickling
                c_val = pickle.load(fp)
            self.csv = c_val
            self.image = b_val
        
        if(ptype == 'test'):
            with open("dataimage_test.txt", "rb") as fp:   # Unpickling
                b_test = pickle.load(fp)
            with open("datacsv_test.txt", "rb") as fp:   # Unpickling
                c_test = pickle.load(fp)
            self.csv = c_test
            self.image = b_test        

    def __len__(self):#return int: number of mri
        return len(self.image)

    def __getitem__(self, idx):#input the dataset and desires i-th item
        img_name = self.csv[idx][0]
        image = self.image[idx][1]
        group = self.csv[idx][1]
        sample = {'image': image, 'patient_id': img_name, 'groups': group} 

        return sample

In [9]:
ADNI_Data_train = ADNI_Dataset('train')
ADNI_Data_val = ADNI_Dataset('val')
ADNI_Data_test = ADNI_Dataset('test')

dataloader_train = DataLoader(ADNI_Data_train, batch_size=1,
                        shuffle=True, num_workers=4)
dataloader_val = DataLoader(ADNI_Data_val, batch_size=1,
                        shuffle=True, num_workers=4)
dataloader_test = DataLoader(ADNI_Data_test, batch_size=1,
                        shuffle=True, num_workers=4)


In [ ]:
#design the network configuration
import torch.nn as nn
import torch.nn.functional as F

#initial: 256*256*160 * 1(feature map number)
#128*128*80 * 2
#64*64*40 * 4
#32*32*20 * 8
#16*16*10 * 16
#8*8*5 * 32
#Linear: 32 * 8 * 8 * 5 
#10000--->1024 --->256 ---> 64 --->3  
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv3d(in_channels = 1, out_channels = 2, kernel_size = 5, padding=2)
        self.conv2 = nn.Conv3d(2, 4, 5, padding=2)
        self.conv3 = nn.Conv3d(4, 8, 5, padding=2)
        self.conv4 = nn.Conv3d(8, 16, 5, padding=2)
        self.conv5 = nn.Conv3d(16, 32, 5, padding=2)
        self.pool = nn.MaxPool3d(2)
        self.fc1 = nn.Linear(32 * 8 * 8 * 5, 1024)
        self.fc2 = nn.Linear(1024, 256)
        self.fc3 = nn.Linear(256, 64)
        self.fc4 = nn.Linear(64, 3)

    def forward(self, x): #batch_size * 256*256*160*1
        x = self.pool(F.relu(self.conv1(x)))#batch_size * 128 * 128 * 80 * 2
        x = self.pool(F.relu(self.conv2(x)))#batch_size * 64 * 64 * 40 * 4
        x = self.pool(F.relu(self.conv3(x)))#batch_size * 32 * 32 * 20 * 8
        x = self.pool(F.relu(self.conv4(x)))#batch_size * 16 * 16 * 10 * 16
        x = self.pool(F.relu(self.conv5(x)))#batch_size * 8 * 8 * 5 * 32
        x = x.view(-1, 32 * 8 * 8 * 5)#batch_size * 10240(8*8*5*32)
        x = F.relu(self.fc1(x))#batch_size * 1024
        x = F.relu(self.fc2(x))#batch_size * 256
        x = F.relu(self.fc3(x))#batch_size * 64
        x = self.fc4(x)#batch_size * 3
        return x

#net = Net().cuda()

print("finished")

In [10]:
#design another network configuration

import torch.nn as nn
import torch.nn.functional as F
class Light_Net(nn.Module):
    def __init__(self):
        super(Light_Net, self).__init__()
        self.conv1 = nn.Conv3d(in_channels = 1, out_channels = 2, kernel_size = 5, padding=2)
        self.conv2 = nn.Conv3d(2, 4, 5, padding=2)
        self.conv3 = nn.Conv3d(4, 8, 5, padding=2)
        self.conv4 = nn.Conv3d(8, 8, 5, padding=2)
        self.conv5 = nn.Conv3d(8, 8, 5, padding=2)
        self.pool = nn.MaxPool3d(2)
        self.fc1 = nn.Linear(8 * 8 * 8 * 5, 1024)
        self.fc2 = nn.Linear(1024, 256)
        self.fc3 = nn.Linear(256, 64)
        self.fc4 = nn.Linear(64, 3)

    def forward(self, x): #batch_size * 256*256*160*1
        x = self.pool(F.relu(self.conv1(x)))#batch_size * 128 * 128 * 80 * 2
        x = self.pool(F.relu(self.conv2(x)))#batch_size * 64 * 64 * 40 * 4
        x = self.pool(F.relu(self.conv3(x)))#batch_size * 32 * 32 * 20 * 8
        x = self.pool(F.relu(self.conv4(x)))#batch_size * 16 * 16 * 10 * 16
        x = self.pool(F.relu(self.conv5(x)))#batch_size * 8 * 8 * 5 * 32
        x = x.view(-1, 8 * 8 * 8 * 5)#batch_size * 10240(8*8*5*32)
        x = F.relu(self.fc1(x))#batch_size * 1024
        x = F.relu(self.fc2(x))#batch_size * 256
        x = F.relu(self.fc3(x))#batch_size * 64
        x = self.fc4(x)#batch_size * 3
        return x

net = Light_Net().cuda()

In [17]:
#define the criterion and optimizer
import torch.optim as optim
import torch
Weight = torch.tensor([total_num / mci, total_num / ad, total_num / cn])
criterion = nn.CrossEntropyLoss(weight = Weight.cuda())
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

print("finished")

finished


In [19]:
import numpy as np
import torch

def ToTensor(np_array):
    tensor = torch.from_numpy(np_array)
    tensor = tensor.float()
    return tensor

epoch = 50
min_total_loss = 1000000
for i in range(epoch):
    for i_batch, sample_batched in enumerate(dataloader_train):
        print(i_batch,
              sample_batched['patient_id'])

        running_loss = 0.0
        # get the inputs
        labels_arr = np.asarray(sample_batched['groups'])
        labels_arr = labels_arr.astype(np.int)
        labels = ToTensor(labels_arr).cuda()

        images_arr = np.asarray(sample_batched['image'])
        images_arr = images_arr.astype(np.float)
        images_arr = np.expand_dims(images_arr, 1)
        images = ToTensor(images_arr).cuda()

        # zero the parameter gradients
        optimizer.zero_grad()
        
        #before actual training
        net.train()

        # forward + backward + optimize
        outputs = net(images)
        print(outputs)
        print(labels.long())
        loss = criterion(outputs, labels.long())
        loss.backward()
        optimizer.step()

        # print statistics
        print('[%d] loss: %.3f' %
                (i_batch + 1, loss.item()))

    print('Finished Training This Epoch')
    
    #validation for the epoch
    net.eval()
    total_val_loss = 0
    for i_batch, sample_batched in enumerate(dataloader_val):
        print(i_batch,
              sample_batched['patient_id'])

        running_loss = 0.0
        # get the inputs
        labels_arr = np.asarray(sample_batched['groups'])
        labels_arr = labels_arr.astype(np.int)
        labels = ToTensor(labels_arr).cuda()

        images_arr = np.asarray(sample_batched['image'])
        images_arr = images_arr.astype(np.float)
        images_arr = np.expand_dims(images_arr, 1)
        images = ToTensor(images_arr).cuda()
        
        outputs = net(images)
        loss = criterion(outputs, labels.long())
        print('Validation')
        print('[%d] loss: %.3f' %
                (i_batch + 1, loss.item()))
        print('\n')
        total_val_loss = total_val_loss + loss.cpu().data.numpy()
        
    print('Start a new epoch')
    #the best model is picked among all epoches
    if(total_val_loss < min_total_loss):
        min_total_loss = total_val_loss
   
    #save model
    #best_model
    torch.save(net, 'best_model_Jan12_3classes.pkl')

print("Best Model generated")

0 ['"012_S_0689"']
tensor([[ 0.1645, -0.1659,  0.0468]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[1] loss: 1.289
1 ['"037_S_0303"']
tensor([[ 0.1647, -0.1658,  0.0465]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[2] loss: 1.076
2 ['"023_S_1247"']
tensor([[ 0.1644, -0.1660,  0.0470]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[3] loss: 0.959
3 ['"002_S_1070"']
tensor([[ 0.1649, -0.1666,  0.0471]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[4] loss: 0.958
4 ['"100_S_0015"']
tensor([[ 0.1661, -0.1674,  0.0467]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[5] loss: 1.076
5 ['"023_S_0604"']
tensor([[ 0.1667, -0.1684,  0.0472]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[6] loss: 0.956
6 ['"130_S_0449"']
tensor([[ 0.1680, -0.1697,  0.0472]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cud

[63] loss: 1.322
63 ['"116_S_0649"']
tensor([[ 0.1852, -0.1966,  0.0581]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[64] loss: 0.941
64 ['"002_S_0954"']
tensor([[ 0.1863, -0.1980,  0.0585]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[65] loss: 0.940
65 ['"031_S_1209"']
tensor([[ 0.1880, -0.1996,  0.0584]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[66] loss: 1.326
66 ['"012_S_1292"']
tensor([[ 0.1890, -0.2002,  0.0580]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[67] loss: 0.938
67 ['"094_S_1293"']
tensor([[ 0.1907, -0.2010,  0.0572]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[68] loss: 0.936
68 ['"051_S_1331"']
tensor([[ 0.1930, -0.2021,  0.0560]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[69] loss: 0.934
69 ['"130_S_0956"']
tensor([[ 0.1957, -0.2034,  0.0546]], device='cuda:0', grad_fn=<ThAddmmBack

/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/serialization.py:241: UserWarning: Couldn't retrieve source code for container of type Light_Net. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "


0 ['"031_S_0830"']
tensor([[ 0.2140, -0.2138,  0.0467]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[1] loss: 0.915
1 ['"005_S_0448"']
tensor([[ 0.2155, -0.2153,  0.0469]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[2] loss: 0.914
2 ['"100_S_0015"']
tensor([[ 0.2175, -0.2170,  0.0467]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[3] loss: 1.083
3 ['"126_S_0606"']
tensor([[ 0.2188, -0.2189,  0.0473]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[4] loss: 1.349
4 ['"116_S_0487"']
tensor([[ 0.2195, -0.2197,  0.0474]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[5] loss: 1.350
5 ['"067_S_1253"']
tensor([[ 0.2196, -0.2195,  0.0471]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[6] loss: 1.350
6 ['"130_S_0449"']
tensor([[ 0.2192, -0.2185,  0.0464]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cud

[56] loss: 0.918
56 ['"051_S_1331"']
tensor([[ 0.2142, -0.2426,  0.0771]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[57] loss: 0.918
57 ['"023_S_1046"']
tensor([[ 0.2150, -0.2429,  0.0766]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[58] loss: 0.918
58 ['"027_S_0417"']
tensor([[ 0.2165, -0.2435,  0.0757]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[59] loss: 0.916
59 ['"023_S_0030"']
tensor([[ 0.2185, -0.2444,  0.0745]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[60] loss: 0.914
60 ['"027_S_0404"']
tensor([[ 0.2211, -0.2455,  0.0731]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[61] loss: 1.379
61 ['"032_S_1101"']
tensor([[ 0.2229, -0.2456,  0.0713]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[62] loss: 1.379
62 ['"136_S_0196"']
tensor([[ 0.2240, -0.2448,  0.0694]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.2619, -0.2660,  0.0530]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[24] loss: 0.876
24 ['"031_S_1209"']
tensor([[ 0.2629, -0.2673,  0.0533]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[25] loss: 1.405
25 ['"023_S_1046"']
tensor([[ 0.2632, -0.2675,  0.0532]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[26] loss: 0.875
26 ['"005_S_0602"']
tensor([[ 0.2643, -0.2680,  0.0527]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[27] loss: 1.086
27 ['"023_S_0061"']
tensor([[ 0.2647, -0.2688,  0.0531]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[28] loss: 1.085
28 ['"027_S_0417"']
tensor([[ 0.2646, -0.2697,  0.0541]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[29] loss: 0.874
29 ['"023_S_0376"']
tensor([[ 0.2653, -0.2709,  0.0547]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

[79] loss: 0.867
79 ['"012_S_0689"']
tensor([[ 0.2775, -0.3105,  0.0841]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[80] loss: 1.455
80 ['"053_S_0507"']
tensor([[ 0.2775, -0.3101,  0.0837]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[81] loss: 0.867
81 ['"018_S_0633"']
tensor([[ 0.2781, -0.3100,  0.0829]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[82] loss: 1.454
82 ['"023_S_0855"']
tensor([[ 0.2782, -0.3090,  0.0818]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[83] loss: 0.866
83 ['"126_S_0606"']
tensor([[ 0.2790, -0.3084,  0.0804]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[84] loss: 1.453
Finished Training This Epoch
0 ['"128_S_1088"']
Validation
[1] loss: 0.865


1 ['"100_S_0190"']
Validation
[2] loss: 0.865


2 ['"130_S_0505"']
Validation
[3] loss: 0.865


3 ['"136_S_0195"']
Validation
[4] loss: 0.865


4 ['"023_S_0388"']
Val

tensor([[ 0.2605, -0.2844,  0.0738]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[47] loss: 0.879
47 ['"027_S_0404"']
tensor([[ 0.2643, -0.2857,  0.0713]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[48] loss: 1.426
48 ['"005_S_0324"']
tensor([[ 0.2672, -0.2859,  0.0686]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[49] loss: 0.873
49 ['"012_S_1321"']
tensor([[ 0.2704, -0.2864,  0.0658]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[50] loss: 0.870
50 ['"007_S_1206"']
tensor([[ 0.2741, -0.2872,  0.0629]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[51] loss: 1.078
51 ['"082_S_1256"']
tensor([[ 0.2769, -0.2881,  0.0610]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[52] loss: 1.081
52 ['"027_S_1081"']
tensor([[ 0.2789, -0.2893,  0.0602]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[

[14] loss: 0.853
14 ['"018_S_0425"']
tensor([[ 0.2937, -0.3218,  0.0795]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[15] loss: 1.068
15 ['"031_S_0830"']
tensor([[ 0.2928, -0.3220,  0.0805]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[16] loss: 0.854
16 ['"130_S_0449"']
tensor([[ 0.2927, -0.3224,  0.0811]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[17] loss: 0.854
17 ['"023_S_0078"']
tensor([[ 0.2933, -0.3231,  0.0812]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[18] loss: 0.854
18 ['"037_S_0303"']
tensor([[ 0.2946, -0.3240,  0.0809]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[19] loss: 1.067
19 ['"127_S_0844"']
tensor([[ 0.2952, -0.3251,  0.0814]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[20] loss: 1.473
20 ['"005_S_0324"']
tensor([[ 0.2952, -0.3251,  0.0814]], device='cuda:0', grad_fn=<ThAddmmBack

[70] loss: 0.824
70 ['"051_S_1072"']
tensor([[ 0.3265, -0.3340,  0.0589]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[71] loss: 0.825
71 ['"018_S_0633"']
tensor([[ 0.3267, -0.3351,  0.0598]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[72] loss: 1.487
72 ['"136_S_0184"']
tensor([[ 0.3263, -0.3352,  0.0603]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[73] loss: 1.091
73 ['"127_S_0393"']
tensor([[ 0.3255, -0.3354,  0.0614]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[74] loss: 0.826
74 ['"027_S_1385"']
tensor([[ 0.3254, -0.3360,  0.0621]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[75] loss: 1.488
75 ['"027_S_1277"']
tensor([[ 0.3247, -0.3355,  0.0623]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[76] loss: 0.827
76 ['"007_S_1222"']
tensor([[ 0.3248, -0.3354,  0.0621]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3015, -0.3434,  0.0943]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[38] loss: 1.494
38 ['"005_S_0324"']
tensor([[ 0.2993, -0.3428,  0.0959]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[39] loss: 0.851
39 ['"037_S_1225"']
tensor([[ 0.2981, -0.3426,  0.0969]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[40] loss: 0.852
40 ['"027_S_1081"']
tensor([[ 0.2977, -0.3428,  0.0975]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[41] loss: 1.493
41 ['"136_S_1227"']
tensor([[ 0.2968, -0.3419,  0.0975]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[42] loss: 0.853
42 ['"051_S_1331"']
tensor([[ 0.2967, -0.3415,  0.0971]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[43] loss: 0.853
43 ['"002_S_0559"']
tensor([[ 0.2973, -0.3413,  0.0964]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

[5] loss: 1.487
5 ['"082_S_1256"']
tensor([[ 0.3068, -0.3365,  0.0816]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[6] loss: 1.068
6 ['"005_S_0814"']
tensor([[ 0.3076, -0.3366,  0.0809]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[7] loss: 1.487
7 ['"094_S_1293"']
tensor([[ 0.3077, -0.3357,  0.0798]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[8] loss: 0.842
8 ['"116_S_0487"']
tensor([[ 0.3086, -0.3352,  0.0784]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[9] loss: 1.485
9 ['"027_S_0404"']
tensor([[ 0.3088, -0.3338,  0.0767]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[10] loss: 1.484
10 ['"126_S_0606"']
tensor([[ 0.3084, -0.3316,  0.0748]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[11] loss: 1.481
11 ['"027_S_0835"']
tensor([[ 0.3074, -0.3287,  0.0726]], device='cuda:0', grad_fn=<ThAddmmBackward>)
ten

[61] loss: 0.833
61 ['"018_S_0406"']
tensor([[ 0.3195, -0.3423,  0.0747]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[62] loss: 0.832
62 ['"037_S_0303"']
tensor([[ 0.3211, -0.3440,  0.0749]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[63] loss: 1.077
63 ['"027_S_1081"']
tensor([[ 0.3221, -0.3458,  0.0758]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[64] loss: 1.498
64 ['"116_S_1249"']
tensor([[ 0.3223, -0.3465,  0.0763]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[65] loss: 1.076
65 ['"027_S_0417"']
tensor([[ 0.3221, -0.3474,  0.0774]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[66] loss: 0.831
66 ['"130_S_0886"']
tensor([[ 0.3226, -0.3484,  0.0781]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[67] loss: 1.075
67 ['"018_S_0369"']
tensor([[ 0.3225, -0.3496,  0.0794]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3019, -0.3429,  0.0932]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[29] loss: 1.493
29 ['"018_S_0633"']
tensor([[ 0.3015, -0.3424,  0.0931]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[30] loss: 1.493
30 ['"016_S_1121"']
tensor([[ 0.3006, -0.3411,  0.0927]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[31] loss: 0.850
31 ['"082_S_1256"']
tensor([[ 0.3005, -0.3402,  0.0918]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[32] loss: 1.058
32 ['"023_S_0855"']
tensor([[ 0.2999, -0.3396,  0.0918]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[33] loss: 0.850
33 ['"023_S_1126"']
tensor([[ 0.3000, -0.3394,  0.0914]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[34] loss: 0.850
34 ['"005_S_0448"']
tensor([[ 0.3008, -0.3394,  0.0907]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

[84] loss: 1.081
Finished Training This Epoch
0 ['"136_S_0195"']
Validation
[1] loss: 0.823


1 ['"130_S_0505"']
Validation
[2] loss: 0.823


2 ['"023_S_0625"']
Validation
[3] loss: 0.823


3 ['"128_S_1088"']
Validation
[4] loss: 0.823


4 ['"023_S_0388"']
Validation
[5] loss: 0.823


5 ['"018_S_0450"']
Validation
[6] loss: 0.823


6 ['"116_S_1232"']
Validation
[7] loss: 1.080


7 ['"127_S_0260"']
Validation
[8] loss: 1.080


8 ['"002_S_0413"']
Validation
[9] loss: 1.080


9 ['"067_S_0607"']
Validation
[10] loss: 0.823


10 ['"100_S_0190"']
Validation
[11] loss: 0.823


11 ['"067_S_0290"']
Validation
[12] loss: 0.823


Start a new epoch
0 ['"051_S_1131"']
tensor([[ 0.3311, -0.3534,  0.0746]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[1] loss: 0.823
1 ['"031_S_0830"']
tensor([[ 0.3323, -0.3552,  0.0752]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[2] loss: 0.822
2 ['"126_S_0606"']
tensor([[ 0.3340, -0.3570,  0.0754]], device

tensor([[ 0.3177, -0.3274,  0.0607]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[52] loss: 0.832
52 ['"136_S_0184"']
tensor([[ 0.3210, -0.3287,  0.0588]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[53] loss: 1.091
53 ['"018_S_0369"']
tensor([[ 0.3234, -0.3302,  0.0578]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[54] loss: 1.093
54 ['"021_S_0332"']
tensor([[ 0.3251, -0.3317,  0.0577]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[55] loss: 0.826
55 ['"023_S_0376"']
tensor([[ 0.3273, -0.3334,  0.0573]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[56] loss: 0.824
56 ['"027_S_0403"']
tensor([[ 0.3299, -0.3352,  0.0565]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[57] loss: 1.095
57 ['"023_S_0604"']
tensor([[ 0.3318, -0.3371,  0.0565]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

[19] loss: 1.064
19 ['"037_S_1225"']
tensor([[ 0.3111, -0.3475,  0.0887]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[20] loss: 0.841
20 ['"023_S_0031"']
tensor([[ 0.3104, -0.3472,  0.0891]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[21] loss: 1.063
21 ['"016_S_1121"']
tensor([[ 0.3093, -0.3473,  0.0902]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[22] loss: 0.842
22 ['"031_S_1209"']
tensor([[ 0.3090, -0.3475,  0.0908]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[23] loss: 1.499
23 ['"021_S_0332"']
tensor([[ 0.3082, -0.3469,  0.0910]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[24] loss: 0.843
24 ['"023_S_1126"']
tensor([[ 0.3081, -0.3465,  0.0907]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[25] loss: 0.843
25 ['"023_S_0030"']
tensor([[ 0.3087, -0.3465,  0.0900]], device='cuda:0', grad_fn=<ThAddmmBack

[75] loss: 0.814
75 ['"018_S_0425"']
tensor([[ 0.3454, -0.3816,  0.0897]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[76] loss: 1.070
76 ['"127_S_0622"']
tensor([[ 0.3445, -0.3818,  0.0908]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[77] loss: 1.069
77 ['"130_S_0449"']
tensor([[ 0.3431, -0.3822,  0.0927]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[78] loss: 0.817
78 ['"031_S_0830"']
tensor([[ 0.3426, -0.3829,  0.0939]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[79] loss: 0.817
79 ['"005_S_0814"']
tensor([[ 0.3428, -0.3838,  0.0947]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[80] loss: 1.544
80 ['"023_S_1046"']
tensor([[ 0.3424, -0.3836,  0.0949]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[81] loss: 0.817
81 ['"023_S_0078"']
tensor([[ 0.3428, -0.3837,  0.0947]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3408, -0.3743,  0.0867]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[43] loss: 1.533
43 ['"023_S_0031"']
tensor([[ 0.3382, -0.3713,  0.0862]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[44] loss: 1.071
44 ['"052_S_1251"']
tensor([[ 0.3353, -0.3689,  0.0865]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[45] loss: 1.070
45 ['"051_S_1072"']
tensor([[ 0.3322, -0.3669,  0.0876]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[46] loss: 0.824
46 ['"018_S_0425"']
tensor([[ 0.3301, -0.3655,  0.0882]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[47] loss: 1.068
47 ['"027_S_0417"']
tensor([[ 0.3277, -0.3644,  0.0895]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[48] loss: 0.828
48 ['"002_S_0954"']
tensor([[ 0.3262, -0.3637,  0.0903]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

[10] loss: 0.815
10 ['"130_S_1337"']
tensor([[ 0.3453, -0.3843,  0.0926]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[11] loss: 1.544
11 ['"023_S_1046"']
tensor([[ 0.3452, -0.3831,  0.0915]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[12] loss: 0.815
12 ['"126_S_0606"']
tensor([[ 0.3458, -0.3824,  0.0901]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[13] loss: 1.542
13 ['"021_S_0332"']
tensor([[ 0.3457, -0.3808,  0.0884]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[14] loss: 0.814
14 ['"031_S_0830"']
tensor([[ 0.3464, -0.3796,  0.0866]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[15] loss: 0.813
15 ['"012_S_1292"']
tensor([[ 0.3476, -0.3788,  0.0844]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[16] loss: 0.812
16 ['"127_S_0844"']
tensor([[ 0.3494, -0.3784,  0.0821]], device='cuda:0', grad_fn=<ThAddmmBack

[66] loss: 0.811
66 ['"037_S_1225"']
tensor([[ 0.3482, -0.3831,  0.0884]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[67] loss: 0.812
67 ['"012_S_1321"']
tensor([[ 0.3480, -0.3822,  0.0876]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[68] loss: 0.812
68 ['"023_S_0963"']
tensor([[ 0.3486, -0.3816,  0.0864]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[69] loss: 1.074
69 ['"002_S_1070"']
tensor([[ 0.3485, -0.3814,  0.0862]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[70] loss: 0.811
70 ['"031_S_1209"']
tensor([[ 0.3492, -0.3814,  0.0856]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[71] loss: 1.541
71 ['"023_S_0078"']
tensor([[ 0.3492, -0.3805,  0.0846]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[72] loss: 0.811
72 ['"037_S_0501"']
tensor([[ 0.3498, -0.3799,  0.0833]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3187, -0.3810,  0.1162]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[34] loss: 0.839
34 ['"037_S_0501"']
tensor([[ 0.3186, -0.3800,  0.1153]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[35] loss: 0.839
35 ['"136_S_0579"']
tensor([[ 0.3191, -0.3794,  0.1141]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[36] loss: 0.838
36 ['"027_S_1277"']
tensor([[ 0.3203, -0.3792,  0.1126]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[37] loss: 0.837
37 ['"023_S_1046"']
tensor([[ 0.3221, -0.3793,  0.1109]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[38] loss: 0.835
38 ['"032_S_0677"']
tensor([[ 0.3244, -0.3796,  0.1089]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[39] loss: 1.049
39 ['"116_S_1249"']
tensor([[ 0.3260, -0.3802,  0.1079]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

[1] loss: 1.530
1 ['"037_S_0303"']
tensor([[ 0.3431, -0.3718,  0.0816]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[2] loss: 1.076
2 ['"016_S_1121"']
tensor([[ 0.3418, -0.3721,  0.0832]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[3] loss: 0.816
3 ['"037_S_1225"']
tensor([[ 0.3412, -0.3726,  0.0843]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[4] loss: 0.817
4 ['"051_S_1123"']
tensor([[ 0.3414, -0.3734,  0.0849]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[5] loss: 1.073
5 ['"023_S_0604"']
tensor([[ 0.3411, -0.3743,  0.0862]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[6] loss: 0.817
6 ['"136_S_0184"']
tensor([[ 0.3415, -0.3754,  0.0870]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[7] loss: 1.071
7 ['"023_S_0061"']
tensor([[ 0.3413, -0.3766,  0.0885]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor(

[57] loss: 0.823
57 ['"116_S_0392"']
tensor([[ 0.3369, -0.3856,  0.1025]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[58] loss: 1.545
58 ['"031_S_0830"']
tensor([[ 0.3367, -0.3858,  0.1028]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[59] loss: 0.823
59 ['"018_S_0425"']
tensor([[ 0.3372, -0.3861,  0.1027]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[60] loss: 1.057
60 ['"005_S_0602"']
tensor([[ 0.3372, -0.3867,  0.1033]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[61] loss: 1.056
61 ['"023_S_0963"']
tensor([[ 0.3366, -0.3875,  0.1047]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[62] loss: 1.055
62 ['"005_S_0324"']
tensor([[ 0.3356, -0.3884,  0.1067]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[63] loss: 0.824
63 ['"067_S_1253"']
tensor([[ 0.3354, -0.3895,  0.1081]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3655, -0.3885,  0.0763]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[25] loss: 0.797
25 ['"027_S_1277"']
tensor([[ 0.3655, -0.3895,  0.0774]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[26] loss: 0.797
26 ['"023_S_1126"']
tensor([[ 0.3661, -0.3906,  0.0780]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[27] loss: 0.797
27 ['"116_S_0649"']
tensor([[ 0.3673, -0.3919,  0.0781]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[28] loss: 0.796
28 ['"023_S_0916"']
tensor([[ 0.3691, -0.3934,  0.0778]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[29] loss: 1.557
29 ['"082_S_1256"']
tensor([[ 0.3702, -0.3938,  0.0772]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[30] loss: 1.087
30 ['"023_S_0855"']
tensor([[ 0.3705, -0.3943,  0.0774]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

[80] loss: 1.073
80 ['"037_S_1225"']
tensor([[ 0.3420, -0.3752,  0.0862]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[81] loss: 0.816
81 ['"012_S_1321"']
tensor([[ 0.3416, -0.3747,  0.0861]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[82] loss: 0.817
82 ['"136_S_0184"']
tensor([[ 0.3419, -0.3746,  0.0857]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[83] loss: 1.073
83 ['"136_S_0196"']
tensor([[ 0.3416, -0.3747,  0.0861]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[84] loss: 1.072
Finished Training This Epoch
0 ['"023_S_0388"']
Validation
[1] loss: 0.817


1 ['"130_S_0505"']
Validation
[2] loss: 0.817


2 ['"127_S_0260"']
Validation
[3] loss: 1.071


3 ['"136_S_0195"']
Validation
[4] loss: 0.817


4 ['"128_S_1088"']
Validation
[5] loss: 0.817


5 ['"100_S_0190"']
Validation
[6] loss: 0.817


6 ['"002_S_0413"']
Validation
[7] loss: 1.071


7 ['"116_S_1232"']
Validat

tensor([[ 0.3207, -0.3571,  0.0887]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[48] loss: 1.511
48 ['"032_S_1169"']
tensor([[ 0.3193, -0.3561,  0.0891]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[49] loss: 1.065
49 ['"023_S_0031"']
tensor([[ 0.3175, -0.3556,  0.0903]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[50] loss: 1.063
50 ['"005_S_0814"']
tensor([[ 0.3155, -0.3553,  0.0922]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[51] loss: 1.509
51 ['"021_S_0332"']
tensor([[ 0.3130, -0.3541,  0.0934]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[52] loss: 0.840
52 ['"023_S_0030"']
tensor([[ 0.3115, -0.3533,  0.0941]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[53] loss: 0.841
53 ['"012_S_1009"']
tensor([[ 0.3108, -0.3529,  0.0944]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

[15] loss: 0.826
15 ['"052_S_1251"']
tensor([[ 0.3309, -0.3723,  0.0944]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[16] loss: 1.063
16 ['"130_S_0969"']
tensor([[ 0.3301, -0.3715,  0.0944]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[17] loss: 1.062
17 ['"051_S_1072"']
tensor([[ 0.3289, -0.3711,  0.0951]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[18] loss: 0.828
18 ['"007_S_1222"']
tensor([[ 0.3285, -0.3709,  0.0954]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[19] loss: 1.061
19 ['"023_S_1126"']
tensor([[ 0.3276, -0.3710,  0.0964]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[20] loss: 0.829
20 ['"023_S_1190"']
tensor([[ 0.3275, -0.3714,  0.0969]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[21] loss: 1.060
21 ['"116_S_0392"']
tensor([[ 0.3269, -0.3720,  0.0981]], device='cuda:0', grad_fn=<ThAddmmBack

[71] loss: 0.829
71 ['"136_S_0086"']
tensor([[ 0.3320, -0.3838,  0.1054]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[72] loss: 1.053
72 ['"032_S_1169"']
tensor([[ 0.3332, -0.3844,  0.1048]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[73] loss: 1.054
73 ['"002_S_1070"']
tensor([[ 0.3338, -0.3852,  0.1051]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[74] loss: 0.825
74 ['"023_S_0061"']
tensor([[ 0.3350, -0.3862,  0.1049]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[75] loss: 1.055
75 ['"067_S_1253"']
tensor([[ 0.3356, -0.3873,  0.1055]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[76] loss: 1.547
76 ['"128_S_1148"']
tensor([[ 0.3355, -0.3874,  0.1056]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[77] loss: 0.824
77 ['"023_S_0030"']
tensor([[ 0.3361, -0.3877,  0.1053]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3264, -0.3730,  0.0997]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[39] loss: 1.057
39 ['"023_S_0031"']
tensor([[ 0.3250, -0.3732,  0.1014]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[40] loss: 1.055
40 ['"027_S_0835"']
tensor([[ 0.3232, -0.3736,  0.1036]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[41] loss: 0.833
41 ['"027_S_0417"']
tensor([[ 0.3223, -0.3743,  0.1052]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[42] loss: 0.834
42 ['"005_S_0553"']
tensor([[ 0.3222, -0.3752,  0.1062]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[43] loss: 1.050
43 ['"067_S_1253"']
tensor([[ 0.3217, -0.3762,  0.1079]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[44] loss: 1.533
44 ['"136_S_0196"']
tensor([[ 0.3205, -0.3762,  0.1090]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

[6] loss: 1.061
6 ['"023_S_0916"']
tensor([[ 0.3410, -0.3875,  0.1001]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[7] loss: 1.548
7 ['"027_S_0417"']
tensor([[ 0.3397, -0.3866,  0.1004]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[8] loss: 0.820
8 ['"005_S_0324"']
tensor([[ 0.3393, -0.3861,  0.1003]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[9] loss: 0.821
9 ['"005_S_0553"']
tensor([[ 0.3395, -0.3859,  0.0999]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[10] loss: 1.060
10 ['"027_S_1385"']
tensor([[ 0.3393, -0.3859,  0.1002]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[11] loss: 1.546
11 ['"002_S_0559"']
tensor([[ 0.3384, -0.3850,  0.1001]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[12] loss: 1.059
12 ['"130_S_0886"']
tensor([[ 0.3372, -0.3845,  0.1008]], device='cuda:0', grad_fn=<ThAddmmBackward>)
t

[62] loss: 0.812
62 ['"100_S_0015"']
tensor([[ 0.3494, -0.3903,  0.0944]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[63] loss: 1.067
63 ['"018_S_0633"']
tensor([[ 0.3490, -0.3916,  0.0962]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[64] loss: 1.553
64 ['"023_S_0376"']
tensor([[ 0.3481, -0.3918,  0.0975]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[65] loss: 0.813
65 ['"031_S_1209"']
tensor([[ 0.3479, -0.3923,  0.0982]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[66] loss: 1.554
66 ['"130_S_0449"']
tensor([[ 0.3471, -0.3918,  0.0984]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[67] loss: 0.814
67 ['"116_S_0649"']
tensor([[ 0.3471, -0.3916,  0.0981]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[68] loss: 0.814
68 ['"023_S_0031"']
tensor([[ 0.3478, -0.3917,  0.0975]], device='cuda:0', grad_fn=<ThAddmmBack

[30] loss: 0.830
30 ['"127_S_0844"']
tensor([[ 0.3289, -0.3891,  0.1141]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[31] loss: 1.548
31 ['"032_S_1169"']
tensor([[ 0.3281, -0.3881,  0.1139]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[32] loss: 1.045
32 ['"016_S_0769"']
tensor([[ 0.3269, -0.3875,  0.1145]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[33] loss: 0.832
33 ['"023_S_0604"']
tensor([[ 0.3264, -0.3872,  0.1146]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[34] loss: 0.832
34 ['"100_S_0015"']
tensor([[ 0.3268, -0.3872,  0.1143]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[35] loss: 1.045
35 ['"027_S_0404"']
tensor([[ 0.3265, -0.3875,  0.1148]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[36] loss: 1.546
36 ['"023_S_0030"']
tensor([[ 0.3258, -0.3868,  0.1148]], device='cuda:0', grad_fn=<ThAddmmBack

[4] loss: 0.820


4 ['"002_S_0413"']
Validation
[5] loss: 1.063


5 ['"128_S_1088"']
Validation
[6] loss: 0.820


6 ['"018_S_0450"']
Validation
[7] loss: 0.820


7 ['"067_S_0290"']
Validation
[8] loss: 0.820


8 ['"023_S_0388"']
Validation
[9] loss: 0.820


9 ['"127_S_0260"']
Validation
[10] loss: 1.063


10 ['"116_S_1232"']
Validation
[11] loss: 1.063


11 ['"100_S_0190"']
Validation
[12] loss: 0.820


Start a new epoch
0 ['"027_S_0404"']
tensor([[ 0.3386, -0.3818,  0.0964]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[1] loss: 1.541
1 ['"032_S_0677"']
tensor([[ 0.3386, -0.3813,  0.0959]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[2] loss: 1.063
2 ['"002_S_0559"']
tensor([[ 0.3381, -0.3810,  0.0961]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[3] loss: 1.063
3 ['"027_S_1385"']
tensor([[ 0.3372, -0.3810,  0.0971]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[4] los

[53] loss: 1.561
53 ['"136_S_0579"']
tensor([[ 0.3248, -0.3994,  0.1291]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[54] loss: 0.836
54 ['"032_S_1169"']
tensor([[ 0.3254, -0.3988,  0.1279]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[55] loss: 1.033
55 ['"037_S_0303"']
tensor([[ 0.3254, -0.3984,  0.1275]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[56] loss: 1.033
56 ['"007_S_1222"']
tensor([[ 0.3248, -0.3983,  0.1279]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[57] loss: 1.033
57 ['"052_S_1251"']
tensor([[ 0.3239, -0.3985,  0.1291]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[58] loss: 1.031
58 ['"100_S_0015"']
tensor([[ 0.3225, -0.3989,  0.1309]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[59] loss: 1.030
59 ['"023_S_0604"']
tensor([[ 0.3207, -0.3995,  0.1333]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3596, -0.4066,  0.1012]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[21] loss: 0.805
21 ['"027_S_0403"']
tensor([[ 0.3614, -0.4088,  0.1017]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[22] loss: 1.064
22 ['"016_S_0769"']
tensor([[ 0.3624, -0.4110,  0.1030]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[23] loss: 0.803
23 ['"127_S_0393"']
tensor([[ 0.3641, -0.4133,  0.1037]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[24] loss: 0.802
24 ['"082_S_0928"']
tensor([[ 0.3662, -0.4156,  0.1039]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[25] loss: 0.801
25 ['"127_S_0622"']
tensor([[ 0.3689, -0.4179,  0.1037]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[26] loss: 1.064
26 ['"012_S_1321"']
tensor([[ 0.3707, -0.4203,  0.1043]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

[76] loss: 1.594
76 ['"032_S_1101"']
tensor([[ 0.3627, -0.4240,  0.1165]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[77] loss: 1.592
77 ['"136_S_0579"']
tensor([[ 0.3612, -0.4212,  0.1149]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[78] loss: 0.806
78 ['"126_S_0606"']
tensor([[ 0.3606, -0.4189,  0.1131]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[79] loss: 1.586
79 ['"023_S_0963"']
tensor([[ 0.3594, -0.4158,  0.1111]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[80] loss: 1.055
80 ['"116_S_0487"']
tensor([[ 0.3578, -0.4133,  0.1100]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[81] loss: 1.579
81 ['"027_S_1277"']
tensor([[ 0.3558, -0.4100,  0.1086]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[82] loss: 0.809
82 ['"005_S_0814"']
tensor([[ 0.3547, -0.4073,  0.1069]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3655, -0.3776,  0.0645]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[44] loss: 1.097
44 ['"127_S_0393"']
tensor([[ 0.3664, -0.3793,  0.0653]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[45] loss: 0.795
45 ['"136_S_0196"']
tensor([[ 0.3680, -0.3811,  0.0657]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[46] loss: 1.096
46 ['"023_S_1046"']
tensor([[ 0.3688, -0.3830,  0.0668]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[47] loss: 0.793
47 ['"023_S_1247"']
tensor([[ 0.3703, -0.3850,  0.0674]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[48] loss: 0.792
48 ['"007_S_1206"']
tensor([[ 0.3723, -0.3870,  0.0676]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[49] loss: 1.096
49 ['"037_S_0303"']
tensor([[ 0.3735, -0.3891,  0.0685]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

[11] loss: 0.823
11 ['"023_S_0031"']
tensor([[ 0.3321, -0.3661,  0.0863]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[12] loss: 1.070
12 ['"021_S_0332"']
tensor([[ 0.3308, -0.3650,  0.0865]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[13] loss: 0.825
13 ['"136_S_0579"']
tensor([[ 0.3303, -0.3643,  0.0863]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[14] loss: 0.825
14 ['"053_S_0507"']
tensor([[ 0.3305, -0.3641,  0.0857]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[15] loss: 0.825
15 ['"136_S_0196"']
tensor([[ 0.3314, -0.3641,  0.0849]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[16] loss: 1.071
16 ['"027_S_1081"']
tensor([[ 0.3317, -0.3643,  0.0848]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[17] loss: 1.520
17 ['"012_S_0689"']
tensor([[ 0.3314, -0.3636,  0.0844]], device='cuda:0', grad_fn=<ThAddmmBack

[67] loss: 0.855
67 ['"116_S_0392"']
tensor([[ 0.3008, -0.3732,  0.1257]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[68] loss: 1.528
68 ['"136_S_0086"']
tensor([[ 0.3015, -0.3729,  0.1247]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[69] loss: 1.030
69 ['"027_S_0835"']
tensor([[ 0.3016, -0.3729,  0.1245]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[70] loss: 0.853
70 ['"002_S_1070"']
tensor([[ 0.3024, -0.3731,  0.1240]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[71] loss: 0.853
71 ['"127_S_0393"']
tensor([[ 0.3038, -0.3736,  0.1231]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[72] loss: 0.851
72 ['"130_S_0449"']
tensor([[ 0.3058, -0.3744,  0.1219]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[73] loss: 0.850
73 ['"127_S_0844"']
tensor([[ 0.3082, -0.3753,  0.1203]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3787, -0.3804,  0.0539]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[35] loss: 0.784
35 ['"018_S_0633"']
tensor([[ 0.3793, -0.3808,  0.0538]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[36] loss: 1.544
36 ['"012_S_1009"']
tensor([[ 0.3792, -0.3803,  0.0532]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[37] loss: 1.110
37 ['"027_S_1082"']
tensor([[ 0.3786, -0.3800,  0.0536]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[38] loss: 1.543
38 ['"126_S_0606"']
tensor([[ 0.3774, -0.3787,  0.0534]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[39] loss: 1.541
39 ['"032_S_1101"']
tensor([[ 0.3758, -0.3767,  0.0529]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[40] loss: 1.539
40 ['"023_S_0963"']
tensor([[ 0.3737, -0.3738,  0.0521]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

[2] loss: 0.827
2 ['"023_S_0030"']
tensor([[ 0.3310, -0.3664,  0.0876]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[3] loss: 0.825
3 ['"023_S_0078"']
tensor([[ 0.3339, -0.3686,  0.0870]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[4] loss: 0.823
4 ['"116_S_0382"']
tensor([[ 0.3372, -0.3708,  0.0860]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[5] loss: 1.071
5 ['"082_S_0928"']
tensor([[ 0.3396, -0.3731,  0.0859]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[6] loss: 0.818
6 ['"027_S_1081"']
tensor([[ 0.3425, -0.3755,  0.0855]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[7] loss: 1.534
7 ['"037_S_0501"']
tensor([[ 0.3445, -0.3766,  0.0846]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[8] loss: 0.814
8 ['"128_S_1148"']
tensor([[ 0.3471, -0.3779,  0.0835]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor(

[58] loss: 1.084
58 ['"037_S_1225"']
tensor([[ 0.3397, -0.3629,  0.0751]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[59] loss: 0.817
59 ['"005_S_0324"']
tensor([[ 0.3389, -0.3642,  0.0772]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[60] loss: 0.817
60 ['"116_S_0392"']
tensor([[ 0.3390, -0.3657,  0.0787]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[61] loss: 1.522
61 ['"018_S_0406"']
tensor([[ 0.3384, -0.3660,  0.0796]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[62] loss: 0.818
62 ['"002_S_1261"']
tensor([[ 0.3386, -0.3666,  0.0801]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[63] loss: 1.077
63 ['"136_S_1227"']
tensor([[ 0.3383, -0.3674,  0.0813]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[64] loss: 0.819
64 ['"027_S_0417"']
tensor([[ 0.3386, -0.3684,  0.0819]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3347, -0.3538,  0.0704]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[26] loss: 1.508
26 ['"023_S_0855"']
tensor([[ 0.3337, -0.3524,  0.0701]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[27] loss: 0.821
27 ['"018_S_0369"']
tensor([[ 0.3334, -0.3515,  0.0694]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[28] loss: 1.085
28 ['"037_S_1225"']
tensor([[ 0.3326, -0.3509,  0.0696]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[29] loss: 0.821
29 ['"116_S_0649"']
tensor([[ 0.3326, -0.3506,  0.0693]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[30] loss: 0.821
30 ['"082_S_1256"']
tensor([[ 0.3332, -0.3507,  0.0687]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[31] loss: 1.085
31 ['"023_S_0916"']
tensor([[ 0.3333, -0.3510,  0.0689]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[

[81] loss: 0.844
81 ['"053_S_0507"']
tensor([[ 0.3117, -0.3686,  0.1095]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[82] loss: 0.843
82 ['"005_S_0448"']
tensor([[ 0.3138, -0.3698,  0.1086]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[83] loss: 0.841
83 ['"027_S_0403"']
tensor([[ 0.3164, -0.3711,  0.1074]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[84] loss: 1.048
Finished Training This Epoch
0 ['"067_S_0607"']
Validation
[1] loss: 0.838


1 ['"002_S_0413"']
Validation
[2] loss: 1.049


2 ['"023_S_0388"']
Validation
[3] loss: 0.838


3 ['"116_S_1232"']
Validation
[4] loss: 1.049


4 ['"130_S_0505"']
Validation
[5] loss: 0.838


5 ['"067_S_0290"']
Validation
[6] loss: 0.838


6 ['"128_S_1088"']
Validation
[7] loss: 0.838


7 ['"018_S_0450"']
Validation
[8] loss: 0.838


8 ['"136_S_0195"']
Validation
[9] loss: 0.838


9 ['"100_S_0190"']
Validation
[10] loss: 0.838


10 ['"023_S_0625"']
Validatio

tensor([[ 0.3030, -0.3534,  0.1023]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[49] loss: 0.849
49 ['"051_S_1072"']
tensor([[ 0.3034, -0.3538,  0.1023]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[50] loss: 0.848
50 ['"005_S_0602"']
tensor([[ 0.3045, -0.3545,  0.1018]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[51] loss: 1.050
51 ['"005_S_0814"']
tensor([[ 0.3050, -0.3553,  0.1022]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[52] loss: 1.508
52 ['"023_S_1247"']
tensor([[ 0.3049, -0.3551,  0.1022]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[53] loss: 0.847
53 ['"012_S_1009"']
tensor([[ 0.3055, -0.3553,  0.1017]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[54] loss: 1.051
54 ['"100_S_0015"']
tensor([[ 0.3056, -0.3556,  0.1020]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

[16] loss: 0.837
16 ['"136_S_0579"']
tensor([[ 0.3202, -0.3890,  0.1223]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[17] loss: 0.838
17 ['"023_S_0030"']
tensor([[ 0.3195, -0.3884,  0.1224]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[18] loss: 0.839
18 ['"005_S_0448"']
tensor([[ 0.3196, -0.3882,  0.1221]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[19] loss: 0.839
19 ['"027_S_0404"']
tensor([[ 0.3204, -0.3883,  0.1215]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[20] loss: 1.547
20 ['"051_S_1072"']
tensor([[ 0.3205, -0.3874,  0.1204]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[21] loss: 0.838
21 ['"016_S_1121"']
tensor([[ 0.3213, -0.3869,  0.1191]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[22] loss: 0.837
22 ['"127_S_0622"']
tensor([[ 0.3227, -0.3867,  0.1174]], device='cuda:0', grad_fn=<ThAddmmBack

[72] loss: 1.573
72 ['"126_S_0606"']
tensor([[ 0.3603, -0.4066,  0.1000]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[73] loss: 1.571
73 ['"136_S_0196"']
tensor([[ 0.3584, -0.4041,  0.0993]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[74] loss: 1.065
74 ['"130_S_0956"']
tensor([[ 0.3562, -0.4021,  0.0995]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[75] loss: 1.566
75 ['"037_S_1225"']
tensor([[ 0.3536, -0.3993,  0.0992]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[76] loss: 0.809
76 ['"082_S_1256"']
tensor([[ 0.3520, -0.3971,  0.0985]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[77] loss: 1.064
77 ['"002_S_0954"']
tensor([[ 0.3500, -0.3953,  0.0987]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[78] loss: 0.812
78 ['"052_S_1251"']
tensor([[ 0.3488, -0.3940,  0.0984]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3253, -0.3754,  0.1027]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[40] loss: 1.054
40 ['"136_S_0579"']
tensor([[ 0.3226, -0.3745,  0.1045]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[41] loss: 0.834
41 ['"027_S_1082"']
tensor([[ 0.3210, -0.3741,  0.1057]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[42] loss: 1.530
42 ['"032_S_1101"']
tensor([[ 0.3189, -0.3727,  0.1064]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[43] loss: 1.529
43 ['"023_S_1126"']
tensor([[ 0.3165, -0.3705,  0.1065]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[44] loss: 0.839
44 ['"127_S_0622"']
tensor([[ 0.3150, -0.3688,  0.1063]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[45] loss: 1.049
45 ['"067_S_1253"']
tensor([[ 0.3131, -0.3675,  0.1068]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[

[7] loss: 1.059
7 ['"116_S_1249"']
tensor([[ 0.3412, -0.3903,  0.1023]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[8] loss: 1.058
8 ['"031_S_1209"']
tensor([[ 0.3415, -0.3921,  0.1039]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[9] loss: 1.553
9 ['"051_S_1072"']
tensor([[ 0.3411, -0.3927,  0.1049]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[10] loss: 0.820
10 ['"023_S_0031"']
tensor([[ 0.3415, -0.3936,  0.1054]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[11] loss: 1.056
11 ['"116_S_0392"']
tensor([[ 0.3414, -0.3946,  0.1066]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[12] loss: 1.556
12 ['"023_S_0030"']
tensor([[ 0.3406, -0.3945,  0.1072]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[13] loss: 0.820
13 ['"037_S_0501"']
tensor([[ 0.3407, -0.3947,  0.1074]], device='cuda:0', grad_fn=<ThAddmmBackward>)

[63] loss: 0.811
63 ['"130_S_0886"']
tensor([[ 0.3482, -0.3676,  0.0712]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[64] loss: 1.087
64 ['"027_S_1081"']
tensor([[ 0.3491, -0.3693,  0.0720]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[65] loss: 1.527
65 ['"007_S_1206"']
tensor([[ 0.3494, -0.3699,  0.0723]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[66] loss: 1.086
66 ['"012_S_1009"']
tensor([[ 0.3491, -0.3706,  0.0734]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[67] loss: 1.085
67 ['"031_S_0830"']
tensor([[ 0.3483, -0.3715,  0.0752]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[68] loss: 0.810
68 ['"005_S_0814"']
tensor([[ 0.3483, -0.3726,  0.0763]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[69] loss: 1.531
69 ['"051_S_1123"']
tensor([[ 0.3476, -0.3726,  0.0770]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3630, -0.3928,  0.0826]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[31] loss: 1.080
31 ['"136_S_0086"']
tensor([[ 0.3629, -0.3943,  0.0843]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[32] loss: 1.079
32 ['"023_S_0916"']
tensor([[ 0.3623, -0.3959,  0.0866]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[33] loss: 1.559
33 ['"130_S_0956"']
tensor([[ 0.3612, -0.3963,  0.0882]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[34] loss: 1.559
34 ['"005_S_0814"']
tensor([[ 0.3596, -0.3957,  0.0892]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[35] loss: 1.559
35 ['"130_S_0969"']
tensor([[ 0.3575, -0.3943,  0.0897]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[36] loss: 1.073
36 ['"018_S_0633"']
tensor([[ 0.3552, -0.3931,  0.0910]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[

[5] loss: 0.816


5 ['"128_S_1088"']
Validation
[6] loss: 0.816


6 ['"136_S_0195"']
Validation
[7] loss: 0.816


7 ['"116_S_1232"']
Validation
[8] loss: 1.076


8 ['"023_S_0388"']
Validation
[9] loss: 0.816


9 ['"130_S_0505"']
Validation
[10] loss: 0.816


10 ['"018_S_0450"']
Validation
[11] loss: 0.816


11 ['"002_S_0413"']
Validation
[12] loss: 1.076


Start a new epoch
0 ['"082_S_0928"']
tensor([[ 0.3423, -0.3724,  0.0822]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[1] loss: 0.816
1 ['"032_S_0677"']
tensor([[ 0.3431, -0.3744,  0.0835]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[2] loss: 1.075
2 ['"018_S_0633"']
tensor([[ 0.3433, -0.3764,  0.0854]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[3] loss: 1.535
3 ['"037_S_0303"']
tensor([[ 0.3429, -0.3773,  0.0867]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[4] loss: 1.072
4 ['"130_S_0449"']
tensor([[ 0.3420, -0

tensor([[ 0.3579, -0.4017,  0.0972]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[54] loss: 1.066
54 ['"023_S_0031"']
tensor([[ 0.3565, -0.4021,  0.0991]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[55] loss: 1.065
55 ['"130_S_0969"']
tensor([[ 0.3547, -0.4027,  0.1015]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[56] loss: 1.062
56 ['"027_S_0404"']
tensor([[ 0.3525, -0.4035,  0.1045]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[57] loss: 1.567
57 ['"027_S_0835"']
tensor([[ 0.3500, -0.4032,  0.1068]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[58] loss: 0.813
58 ['"005_S_0324"']
tensor([[ 0.3484, -0.4033,  0.1085]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[59] loss: 0.815
59 ['"053_S_0507"']
tensor([[ 0.3477, -0.4036,  0.1095]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

[21] loss: 0.818
21 ['"023_S_0078"']
tensor([[ 0.3444, -0.3926,  0.1013]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[22] loss: 0.817
22 ['"128_S_1148"']
tensor([[ 0.3468, -0.3940,  0.1003]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[23] loss: 0.815
23 ['"007_S_1222"']
tensor([[ 0.3496, -0.3954,  0.0990]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[24] loss: 1.063
24 ['"002_S_1261"']
tensor([[ 0.3517, -0.3970,  0.0985]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[25] loss: 1.064
25 ['"027_S_0404"']
tensor([[ 0.3530, -0.3987,  0.0990]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[26] loss: 1.561
26 ['"002_S_1070"']
tensor([[ 0.3536, -0.3992,  0.0989]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[27] loss: 0.809
27 ['"005_S_0553"']
tensor([[ 0.3548, -0.3999,  0.0984]], device='cuda:0', grad_fn=<ThAddmmBack

[77] loss: 1.072
77 ['"053_S_0507"']
tensor([[ 0.3418, -0.3772,  0.0877]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[78] loss: 0.817
78 ['"051_S_1072"']
tensor([[ 0.3419, -0.3785,  0.0888]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[79] loss: 0.817
79 ['"023_S_0963"']
tensor([[ 0.3428, -0.3799,  0.0895]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[80] loss: 1.069
80 ['"012_S_0689"']
tensor([[ 0.3430, -0.3814,  0.0909]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[81] loss: 1.541
81 ['"136_S_0184"']
tensor([[ 0.3426, -0.3818,  0.0917]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[82] loss: 1.067
82 ['"027_S_1082"']
tensor([[ 0.3417, -0.3824,  0.0932]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[83] loss: 1.542
83 ['"116_S_0649"']
tensor([[ 0.3404, -0.3820,  0.0941]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3202, -0.3610,  0.0925]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[45] loss: 1.515
45 ['"018_S_0633"']
tensor([[ 0.3196, -0.3604,  0.0925]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[46] loss: 1.514
46 ['"002_S_1261"']
tensor([[ 0.3185, -0.3589,  0.0920]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[47] loss: 1.062
47 ['"021_S_0332"']
tensor([[ 0.3171, -0.3578,  0.0923]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[48] loss: 0.836
48 ['"032_S_0677"']
tensor([[ 0.3164, -0.3571,  0.0923]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[49] loss: 1.061
49 ['"136_S_0184"']
tensor([[ 0.3154, -0.3567,  0.0929]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[50] loss: 1.060
50 ['"037_S_0501"']
tensor([[ 0.3139, -0.3566,  0.0943]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

[12] loss: 1.064
12 ['"005_S_0324"']
tensor([[ 0.3468, -0.3932,  0.0994]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[13] loss: 0.814
13 ['"100_S_0015"']
tensor([[ 0.3464, -0.3946,  0.1012]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[14] loss: 1.060
14 ['"023_S_1190"']
tensor([[ 0.3456, -0.3960,  0.1036]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[15] loss: 1.058
15 ['"027_S_1277"']
tensor([[ 0.3443, -0.3976,  0.1066]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[16] loss: 0.817
16 ['"023_S_0061"']
tensor([[ 0.3438, -0.3992,  0.1088]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[17] loss: 1.053
17 ['"023_S_1247"']
tensor([[ 0.3428, -0.4010,  0.1116]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[18] loss: 0.819
18 ['"005_S_0553"']
tensor([[ 0.3427, -0.4028,  0.1137]], device='cuda:0', grad_fn=<ThAddmmBack

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



tensor([[ 0.3353, -0.3653,  0.0813]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[84] loss: 0.821
Finished Training This Epoch
0 ['"116_S_1232"']
Validation
[1] loss: 1.074


1 ['"067_S_0607"']
Validation
[2] loss: 0.820


2 ['"136_S_0195"']
Validation
[3] loss: 0.820


3 ['"023_S_0625"']
Validation
[4] loss: 0.820


4 ['"067_S_0290"']
Validation
[5] loss: 0.820


5 ['"018_S_0450"']
Validation
[6] loss: 0.820


6 ['"100_S_0190"']
Validation
[7] loss: 0.820


7 ['"130_S_0505"']
Validation
[8] loss: 0.820


8 ['"002_S_0413"']
Validation
[9] loss: 1.074


9 ['"023_S_0388"']
Validation
[10] loss: 0.820


10 ['"127_S_0260"']
Validation
[11] loss: 1.074


11 ['"128_S_1088"']
Validation
[12] loss: 0.820


Start a new epoch
0 ['"023_S_0078"']
tensor([[ 0.3366, -0.3671,  0.0820]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[1] loss: 0.820
1 ['"023_S_0963"']
tensor([[ 0.3384, -0.3691,  0.0822]], device='cuda:0', grad_fn=<ThAddmmBackward

[51] loss: 1.515
51 ['"016_S_1121"']
tensor([[ 0.3171, -0.3607,  0.0949]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[52] loss: 0.837
52 ['"136_S_0579"']
tensor([[ 0.3190, -0.3607,  0.0931]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[53] loss: 0.835
53 ['"032_S_1101"']
tensor([[ 0.3213, -0.3611,  0.0911]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[54] loss: 1.515
54 ['"100_S_0015"']
tensor([[ 0.3229, -0.3605,  0.0888]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[55] loss: 1.065
55 ['"023_S_0031"']
tensor([[ 0.3237, -0.3601,  0.0876]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[56] loss: 1.067
56 ['"130_S_0969"']
tensor([[ 0.3241, -0.3601,  0.0872]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[57] loss: 1.067
57 ['"082_S_1256"']
tensor([[ 0.3238, -0.3603,  0.0877]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3408, -0.3941,  0.1061]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[19] loss: 1.055
19 ['"136_S_1227"']
tensor([[ 0.3401, -0.3944,  0.1071]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[20] loss: 0.821
20 ['"094_S_1293"']
tensor([[ 0.3402, -0.3950,  0.1077]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[21] loss: 0.821
21 ['"002_S_1261"']
tensor([[ 0.3409, -0.3958,  0.1078]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[22] loss: 1.053
22 ['"067_S_1253"']
tensor([[ 0.3410, -0.3967,  0.1086]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[23] loss: 1.558
23 ['"027_S_0403"']
tensor([[ 0.3406, -0.3966,  0.1089]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[24] loss: 1.052
24 ['"002_S_0954"']
tensor([[ 0.3397, -0.3967,  0.1100]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

[74] loss: 1.052
74 ['"116_S_0649"']
tensor([[ 0.3133, -0.3652,  0.1036]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[75] loss: 0.841
75 ['"052_S_1251"']
tensor([[ 0.3133, -0.3659,  0.1042]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[76] loss: 1.050
76 ['"031_S_0830"']
tensor([[ 0.3129, -0.3667,  0.1055]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[77] loss: 0.841
77 ['"051_S_1072"']
tensor([[ 0.3132, -0.3677,  0.1063]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[78] loss: 0.841
78 ['"023_S_0604"']
tensor([[ 0.3141, -0.3689,  0.1065]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[79] loss: 0.841
79 ['"023_S_0030"']
tensor([[ 0.3157, -0.3702,  0.1064]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[80] loss: 0.839
80 ['"082_S_0928"']
tensor([[ 0.3177, -0.3717,  0.1059]], device='cuda:0', grad_fn=<ThAddmmBack

[51] loss: 0.810
51 ['"002_S_0954"']
tensor([[ 0.3529, -0.3910,  0.0905]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[52] loss: 0.808
52 ['"027_S_0404"']
tensor([[ 0.3550, -0.3917,  0.0890]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[53] loss: 1.553
53 ['"051_S_1123"']
tensor([[ 0.3563, -0.3913,  0.0873]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[54] loss: 1.074
54 ['"128_S_1148"']
tensor([[ 0.3569, -0.3912,  0.0866]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[55] loss: 0.805
55 ['"037_S_0303"']
tensor([[ 0.3582, -0.3914,  0.0855]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[56] loss: 1.076
56 ['"094_S_1293"']
tensor([[ 0.3588, -0.3918,  0.0853]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[57] loss: 0.803
57 ['"018_S_0369"']
tensor([[ 0.3600, -0.3925,  0.0847]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3332, -0.3921,  0.1117]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[19] loss: 0.827
19 ['"027_S_1277"']
tensor([[ 0.3328, -0.3922,  0.1122]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[20] loss: 0.827
20 ['"116_S_0649"']
tensor([[ 0.3331, -0.3926,  0.1122]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[21] loss: 0.827
21 ['"128_S_1148"']
tensor([[ 0.3341, -0.3932,  0.1119]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[22] loss: 0.826
22 ['"023_S_0963"']
tensor([[ 0.3356, -0.3940,  0.1111]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[23] loss: 1.049
23 ['"012_S_1292"']
tensor([[ 0.3365, -0.3949,  0.1113]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[24] loss: 0.824
24 ['"018_S_0633"']
tensor([[ 0.3380, -0.3961,  0.1110]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[

[74] loss: 1.527
74 ['"005_S_0814"']
tensor([[ 0.3452, -0.3687,  0.0747]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[75] loss: 1.526
75 ['"021_S_0332"']
tensor([[ 0.3435, -0.3675,  0.0750]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[76] loss: 0.813
76 ['"037_S_1225"']
tensor([[ 0.3427, -0.3666,  0.0749]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[77] loss: 0.814
77 ['"023_S_1190"']
tensor([[ 0.3427, -0.3661,  0.0745]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[78] loss: 1.082
78 ['"023_S_1046"']
tensor([[ 0.3421, -0.3659,  0.0748]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[79] loss: 0.815
79 ['"136_S_0184"']
tensor([[ 0.3423, -0.3660,  0.0747]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[80] loss: 1.082
80 ['"018_S_0425"']
tensor([[ 0.3419, -0.3663,  0.0754]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3288, -0.3803,  0.1036]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[42] loss: 0.829
42 ['"023_S_0916"']
tensor([[ 0.3285, -0.3815,  0.1051]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[43] loss: 1.539
43 ['"067_S_1253"']
tensor([[ 0.3277, -0.3816,  0.1061]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[44] loss: 1.539
44 ['"007_S_1206"']
tensor([[ 0.3264, -0.3807,  0.1065]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[45] loss: 1.051
45 ['"005_S_0814"']
tensor([[ 0.3247, -0.3802,  0.1077]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[46] loss: 1.537
46 ['"116_S_0649"']
tensor([[ 0.3226, -0.3787,  0.1083]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[47] loss: 0.834
47 ['"027_S_1385"']
tensor([[ 0.3214, -0.3777,  0.1084]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[

[9] loss: 1.057
9 ['"032_S_1101"']
tensor([[ 0.3291, -0.3778,  0.1006]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[10] loss: 1.535
10 ['"027_S_0404"']
tensor([[ 0.3283, -0.3771,  0.1006]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[11] loss: 1.534
11 ['"130_S_0886"']
tensor([[ 0.3270, -0.3755,  0.1002]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[12] loss: 1.056
12 ['"100_S_0015"']
tensor([[ 0.3254, -0.3743,  0.1007]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[13] loss: 1.056
13 ['"002_S_1261"']
tensor([[ 0.3234, -0.3734,  0.1018]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[14] loss: 1.054
14 ['"005_S_0324"']
tensor([[ 0.3211, -0.3729,  0.1036]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[15] loss: 0.835
15 ['"130_S_1337"']
tensor([[ 0.3197, -0.3727,  0.1048]], device='cuda:0', grad_fn=<ThAddmmBackwa

[65] loss: 1.570
65 ['"130_S_0956"']
tensor([[ 0.3535, -0.4064,  0.1059]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[66] loss: 1.570
66 ['"027_S_0417"']
tensor([[ 0.3534, -0.4053,  0.1048]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[67] loss: 0.810
67 ['"037_S_0501"']
tensor([[ 0.3540, -0.4046,  0.1034]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[68] loss: 0.809
68 ['"094_S_1293"']
tensor([[ 0.3553, -0.4042,  0.1018]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[69] loss: 0.808
69 ['"127_S_0622"']
tensor([[ 0.3570, -0.4042,  0.1000]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[70] loss: 1.064
70 ['"136_S_0429"']
tensor([[ 0.3581, -0.4044,  0.0991]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[71] loss: 0.806
71 ['"005_S_0553"']
tensor([[ 0.3597, -0.4048,  0.0978]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3292, -0.3694,  0.0915]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[33] loss: 0.827
33 ['"018_S_0369"']
tensor([[ 0.3307, -0.3706,  0.0912]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[34] loss: 1.065
34 ['"053_S_0507"']
tensor([[ 0.3316, -0.3719,  0.0917]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[35] loss: 0.825
35 ['"027_S_1081"']
tensor([[ 0.3330, -0.3734,  0.0918]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[36] loss: 1.530
36 ['"031_S_0830"']
tensor([[ 0.3338, -0.3737,  0.0914]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[37] loss: 0.823
37 ['"100_S_0015"']
tensor([[ 0.3351, -0.3743,  0.0907]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[38] loss: 1.066
38 ['"005_S_0553"']
tensor([[ 0.3358, -0.3751,  0.0908]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

[11] loss: 1.094


11 ['"018_S_0450"']
Validation
[12] loss: 0.804


Start a new epoch
Best Model generated


In [22]:
import torch

#load the best_model back 
final_net = torch.load('best_model_Jan12_3classes.pkl')
final_net.eval()
correct_sum = 0.
total_sum = 0.
for i_batch, sample_batched in enumerate(dataloader_test):
    print(i_batch,
          sample_batched['patient_id'])

    running_loss = 0.0
    # get the inputs
    labels_arr = np.asarray(sample_batched['groups'])
    labels_arr = labels_arr.astype(np.int)
    labels = ToTensor(labels_arr).cuda()

    images_arr = np.asarray(sample_batched['image'])
    images_arr = images_arr.astype(np.float)
    images_arr = np.expand_dims(images_arr, 1)
    images = ToTensor(images_arr).cuda()

    outputs = final_net(images)#n * 3
    results_type = np.argmax(outputs.cpu().data.numpy(), axis=1)
    results_type = ToTensor(results_type)
    print(outputs)
    
    
    #calculate accuracy
    labels = labels.cpu()
    print("\n", results_type, " ", labels)
    correct_sum += (labels == results_type)
    total_sum += 1


print("correct_sum_final", correct_sum)
print("total_sum", total_sum)

0 ['"023_S_0058"']
tensor([[ 0.3535, -0.3670,  0.0642]], device='cuda:0', grad_fn=<ThAddmmBackward>)

 tensor([0.])   tensor([2.])
1 ['"052_S_1250"']
tensor([[ 0.3535, -0.3670,  0.0642]], device='cuda:0', grad_fn=<ThAddmmBackward>)

 tensor([0.])   tensor([2.])
2 ['"002_S_1268"']
tensor([[ 0.3535, -0.3670,  0.0642]], device='cuda:0', grad_fn=<ThAddmmBackward>)

 tensor([0.])   tensor([0.])
3 ['"100_S_1286"']
tensor([[ 0.3535, -0.3670,  0.0642]], device='cuda:0', grad_fn=<ThAddmmBackward>)

 tensor([0.])   tensor([2.])
4 ['"016_S_1117"']
tensor([[ 0.3535, -0.3670,  0.0642]], device='cuda:0', grad_fn=<ThAddmmBackward>)

 tensor([0.])   tensor([0.])
5 ['"016_S_1326"']
tensor([[ 0.3535, -0.3670,  0.0642]], device='cuda:0', grad_fn=<ThAddmmBackward>)

 tensor([0.])   tensor([0.])
6 ['"136_S_0194"']
tensor([[ 0.3535, -0.3670,  0.0642]], device='cuda:0', grad_fn=<ThAddmmBackward>)

 tensor([0.])   tensor([1.])
7 ['"027_S_0307"']
tensor([[ 0.3535, -0.3670,  0.0642]], device='cuda:0', grad_fn=<