In [1]:
import csv
from scipy import ndimage
from scipy import linalg
import numpy as np
import nibabel as nib
import os
import glob
import pandas as pd
import matplotlib.pyplot as plt
from operator import itemgetter
import pickle

In [2]:
import random

index = np.array(range(119))
random.seed(40)
random.shuffle(index)

train_index = index[0:84]
val_index = index[84:96]
test_index = index[96:119]

#train_index.astype(np.int64)
#val_index.astype(np.int64)
#test_index.astype(np.int64)

In [13]:
dataimage_train = [dataimage[j] for j in train_index]
print(dataimage_train)

NameError: name 'dataimage' is not defined

In [4]:
from torch.utils.data import Dataset, DataLoader

def ToTensor(np_array):
    tensor = torch.from_numpy(np_array)
    tensor = tensor.float()
    return tensor

class ADNI_Dataset(Dataset):
    
    def __init__(self, ptype, transform=None):
        """
        Args:
            csv_file (string): Path to the csv file with annotations.
            root_dir (string): Directory with all the images.
            transform (callable, optional): Optional transform to be applied
                on a sample.
        """
        if(ptype == 'train'):
            with open("dataimage_train.txt", "rb") as fp:   # Unpickling
                b_train = pickle.load(fp)
            with open("datacsv_train.txt", "rb") as fp:   # Unpickling
                c_train = pickle.load(fp)
            self.csv = c_train
            self.image = b_train
        
        if(ptype == 'val'):
            with open("dataimage_val.txt", "rb") as fp:   # Unpickling
                b_val = pickle.load(fp)
            with open("datacsv_val.txt", "rb") as fp:   # Unpickling
                c_val = pickle.load(fp)
            self.csv = c_val
            self.image = b_val
        
        if(ptype == 'test'):
            with open("dataimage_test.txt", "rb") as fp:   # Unpickling
                b_test = pickle.load(fp)
            with open("datacsv_test.txt", "rb") as fp:   # Unpickling
                c_test = pickle.load(fp)
            self.csv = c_test
            self.image = b_test

        print("great job dude")
        #c[0][0] and b[0][0]'s patient name formats don't conform

        

    def __len__(self):#return int: number of mri
        return len(self.image)

    def __getitem__(self, idx):#input the dataset and desires i-th item
        img_name = self.csv[idx][0]
        image = self.image[idx][1]
        group = self.csv[idx][1]
        sample = {'image': image, 'patient_id': img_name, 'groups': group} 

        return sample


In [5]:
ADNI_Data_train = ADNI_Dataset('train')

ADNI_Data_val = ADNI_Dataset('val')

ADNI_Data_test = ADNI_Dataset('test')



dataloader_train = DataLoader(ADNI_Data_train, batch_size=1,
                        shuffle=True, num_workers=4)
dataloader_val = DataLoader(ADNI_Data_val, batch_size=1,
                        shuffle=True, num_workers=4)
dataloader_test = DataLoader(ADNI_Data_test, batch_size=1,
                        shuffle=True, num_workers=4)

print("finished")

great job dude
great job dude
great job dude
finished


In [6]:
import torch.nn as nn
import torch.nn.functional as F

#initial: 256*256*160 * 1(feature map number)
#128*128*80 * 2
#64*64*40 * 4
#32*32*20 * 8
#16*16*10 * 16
#8*8*5 * 32
#Linear: 32 * 8 * 8 * 5 
#10000--->1024 --->256 ---> 64 --->3  
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv3d(in_channels = 1, out_channels = 2, kernel_size = 5, padding=2)
        self.conv2 = nn.Conv3d(2, 4, 5, padding=2)
        self.conv3 = nn.Conv3d(4, 8, 5, padding=2)
        self.conv4 = nn.Conv3d(8, 16, 5, padding=2)
        self.conv5 = nn.Conv3d(16, 32, 5, padding=2)
        self.pool = nn.MaxPool3d(2)
        self.fc1 = nn.Linear(32 * 8 * 8 * 5, 1024)
        self.fc2 = nn.Linear(1024, 256)
        self.fc3 = nn.Linear(256, 64)
        self.fc4 = nn.Linear(64, 3)

    def forward(self, x): #batch_size * 256*256*160*1
        x = self.pool(F.relu(self.conv1(x)))#batch_size * 128 * 128 * 80 * 2
        x = self.pool(F.relu(self.conv2(x)))#batch_size * 64 * 64 * 40 * 4
        x = self.pool(F.relu(self.conv3(x)))#batch_size * 32 * 32 * 20 * 8
        x = self.pool(F.relu(self.conv4(x)))#batch_size * 16 * 16 * 10 * 16
        x = self.pool(F.relu(self.conv5(x)))#batch_size * 8 * 8 * 5 * 32
        x = x.view(-1, 32 * 8 * 8 * 5)#batch_size * 10240(8*8*5*32)
        x = F.relu(self.fc1(x))#batch_size * 1024
        x = F.relu(self.fc2(x))#batch_size * 256
        x = F.relu(self.fc3(x))#batch_size * 64
        x = self.fc4(x)#batch_size * 3
        return x

net = Net().cuda()

print("finished")

finished


In [97]:
import torch.nn as nn
import torch.nn.functional as F
class Light_Net(nn.Module):
    def __init__(self):
        super(Light_Net, self).__init__()
        self.conv1 = nn.Conv3d(in_channels = 1, out_channels = 2, kernel_size = 5, padding=2)
        self.conv2 = nn.Conv3d(2, 4, 5, padding=2)
        self.conv3 = nn.Conv3d(4, 8, 5, padding=2)
        self.conv4 = nn.Conv3d(8, 8, 5, padding=2)
        self.conv5 = nn.Conv3d(8, 8, 5, padding=2)
        self.pool = nn.MaxPool3d(2)
        self.fc1 = nn.Linear(8 * 8 * 8 * 5, 1024)
        self.fc2 = nn.Linear(1024, 256)
        self.fc3 = nn.Linear(256, 64)
        self.fc4 = nn.Linear(64, 3)

    def forward(self, x): #batch_size * 256*256*160*1
        x = self.pool(F.relu(self.conv1(x)))#batch_size * 128 * 128 * 80 * 2
        x = self.pool(F.relu(self.conv2(x)))#batch_size * 64 * 64 * 40 * 4
        x = self.pool(F.relu(self.conv3(x)))#batch_size * 32 * 32 * 20 * 8
        x = self.pool(F.relu(self.conv4(x)))#batch_size * 16 * 16 * 10 * 16
        x = self.pool(F.relu(self.conv5(x)))#batch_size * 8 * 8 * 5 * 32
        x = x.view(-1, 8 * 8 * 8 * 5)#batch_size * 10240(8*8*5*32)
        x = F.relu(self.fc1(x))#batch_size * 1024
        x = F.relu(self.fc2(x))#batch_size * 256
        x = F.relu(self.fc3(x))#batch_size * 64
        x = self.fc4(x)#batch_size * 3
        return x

#net = Light_Net().cuda()
print("finished")

finished


In [7]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

print("finished")

finished


In [9]:
import numpy as np
import torch

def ToTensor(np_array):
    tensor = torch.from_numpy(np_array)
    tensor = tensor.float()
    return tensor

epoch = 50
min_total_loss = 1000000


for i in range(epoch):
    for i_batch, sample_batched in enumerate(dataloader_train):
        print(i_batch,
              sample_batched['patient_id'])

        running_loss = 0.0
        # get the inputs
        labels_arr = np.asarray(sample_batched['groups'])
        labels_arr = labels_arr.astype(np.int)
        labels = ToTensor(labels_arr).cuda()


        images_arr = np.asarray(sample_batched['image'])
        images_arr = images_arr.astype(np.float)
        images_arr = np.expand_dims(images_arr, 1)
        images = ToTensor(images_arr).cuda()



        # zero the parameter gradients
        optimizer.zero_grad()
        
        #before actual training
        net.train()

        # forward + backward + optimize
        outputs = net(images)
        print(outputs)
        print(labels.long())
        loss = criterion(outputs, labels.long())
        loss.backward()
        optimizer.step()

        # print statistics
        print('[%d] loss: %.3f' %
                (i_batch + 1, loss.item()))

    print('$$Finished Training This Epoch')
    
    #validation for the epoch
    net.eval()
    total_val_loss = 0
    print('Start a new val_epoch')
    for i_batch, sample_batched in enumerate(dataloader_val):
        print(i_batch,
              sample_batched['patient_id'])

        running_loss = 0.0
        # get the inputs
        labels_arr = np.asarray(sample_batched['groups'])
        labels_arr = labels_arr.astype(np.int)
        labels = ToTensor(labels_arr).cuda()

        images_arr = np.asarray(sample_batched['image'])
        images_arr = images_arr.astype(np.float)
        images_arr = np.expand_dims(images_arr, 1)
        images = ToTensor(images_arr).cuda()
        
        outputs = net(images)
        loss = criterion(outputs, labels.long())
        print('Validation')
        print('[%d] loss: %.3f' %
                (i_batch + 1, loss.item()))
        print('\n')
        
        total_val_loss = total_val_loss + loss.cpu().data.numpy()
        
        
    if(total_val_loss < min_total_loss):
        min_total_loss = total_val_loss
   
    #save model
    #best_model
    torch.save(net, 'best_model_2.pkl')

print("we're done training")

0 ['"018_S_0633"']
tensor([[ 0.1275,  0.0321, -0.0733]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[1] loss: 1.099
1 ['"016_S_1121"']
tensor([[ 0.1268,  0.0319, -0.0724]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[2] loss: 1.004
2 ['"027_S_0404"']
tensor([[ 0.1271,  0.0313, -0.0720]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[3] loss: 1.099
3 ['"116_S_0649"']
tensor([[ 0.1268,  0.0316, -0.0721]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[4] loss: 1.004
4 ['"012_S_1009"']
tensor([[ 0.1273,  0.0315, -0.0725]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[5] loss: 1.203
5 ['"136_S_1227"']
tensor([[ 0.1273,  0.0310, -0.0719]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[6] loss: 1.003
6 ['"023_S_0604"']
tensor([[ 0.1281,  0.0301, -0.0718]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cud

[56] loss: 1.212
56 ['"053_S_0507"']
tensor([[ 0.2089, -0.0443, -0.0750]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[57] loss: 0.928
57 ['"012_S_0689"']
tensor([[ 0.2122, -0.0477, -0.0747]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[58] loss: 1.185
58 ['"067_S_1253"']
tensor([[ 0.2148, -0.0499, -0.0749]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[59] loss: 1.187
59 ['"023_S_0916"']
tensor([[ 0.2165, -0.0511, -0.0754]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[60] loss: 1.189
60 ['"037_S_0303"']
tensor([[ 0.2177, -0.0514, -0.0762]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[61] loss: 1.214
61 ['"023_S_1262"']
tensor([[ 0.2182, -0.0520, -0.0761]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[62] loss: 1.190
62 ['"018_S_0369"']
tensor([[ 0.2182, -0.0517, -0.0764]], device='cuda:0', grad_fn=<ThAddmmBack

/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/serialization.py:241: UserWarning: Couldn't retrieve source code for container of type Net. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "


0 ['"012_S_0689"']
tensor([[ 0.1958, -0.0630, -0.0424]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[1] loss: 1.199
1 ['"002_S_0954"']
tensor([[ 0.1943, -0.0640, -0.0399]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[2] loss: 0.941
2 ['"018_S_0406"']
tensor([[ 0.1938, -0.0653, -0.0380]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[3] loss: 0.942
3 ['"027_S_0403"']
tensor([[ 0.1940, -0.0667, -0.0366]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[4] loss: 1.172
4 ['"023_S_0061"']
tensor([[ 0.1937, -0.0685, -0.0346]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[5] loss: 1.170
5 ['"023_S_1262"']
tensor([[ 0.1930, -0.0703, -0.0319]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[6] loss: 1.206
6 ['"037_S_0303"']
tensor([[ 0.1919, -0.0712, -0.0298]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cud

[56] loss: 0.937
56 ['"007_S_1206"']
tensor([[ 0.2027, -0.1046, -0.0057]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[57] loss: 1.143
57 ['"136_S_1227"']
tensor([[ 0.2045, -0.1054, -0.0067]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[58] loss: 0.933
58 ['"023_S_1247"']
tensor([[ 0.2069, -0.1065, -0.0079]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[59] loss: 0.931
59 ['"136_S_0196"']
tensor([[ 0.2098, -0.1078, -0.0095]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[60] loss: 1.148
60 ['"051_S_1123"']
tensor([[ 0.2119, -0.1093, -0.0100]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[61] loss: 1.149
61 ['"005_S_0602"']
tensor([[ 0.2134, -0.1110, -0.0097]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[62] loss: 1.149
62 ['"018_S_0425"']
tensor([[ 0.2142, -0.1128, -0.0085]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([0], device='cuda:0')
[24] loss: 0.869
24 ['"136_S_1227"']
tensor([[ 0.2831, -0.1657, -0.0229]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[25] loss: 0.865
25 ['"130_S_0969"']
tensor([[ 0.2876, -0.1678, -0.0254]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[26] loss: 1.174
26 ['"051_S_1131"']
tensor([[ 0.2912, -0.1700, -0.0267]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[27] loss: 0.858
27 ['"136_S_0184"']
tensor([[ 0.2951, -0.1723, -0.0283]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[28] loss: 1.178
28 ['"012_S_1321"']
tensor([[ 0.2981, -0.1746, -0.0289]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[29] loss: 0.852
29 ['"130_S_0956"']
tensor([[ 0.3015, -0.1771, -0.0298]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[30] loss: 1.328
30 ['"027_S_1082"']
tensor([[ 0.3041, -0.1784, -0.0310]], device='

tensor([2], device='cuda:0')
[80] loss: 1.136
80 ['"053_S_0507"']
tensor([[ 0.2711, -0.1908,  0.0150]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[81] loss: 0.877
81 ['"023_S_0061"']
tensor([[ 0.2696, -0.1913,  0.0170]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[82] loss: 1.131
82 ['"007_S_1222"']
tensor([[ 0.2678, -0.1920,  0.0196]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[83] loss: 1.129
83 ['"031_S_0830"']
tensor([[ 0.2657, -0.1930,  0.0228]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[84] loss: 0.882
$$Finished Training This Epoch
Start a new val_epoch
0 ['"023_S_0625"']
Validation
[1] loss: 0.883


1 ['"002_S_0413"']
Validation
[2] loss: 1.123


2 ['"127_S_0260"']
Validation
[3] loss: 1.123


3 ['"100_S_0190"']
Validation
[4] loss: 0.883


4 ['"023_S_0388"']
Validation
[5] loss: 0.883


5 ['"067_S_0607"']
Validation
[6] loss: 0.883


6 ['"136_S_0195"']
Va

tensor([[ 0.2434, -0.2250,  0.0782]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[62] loss: 0.906
62 ['"052_S_1251"']
tensor([[ 0.2443, -0.2263,  0.0786]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[63] loss: 1.071
63 ['"005_S_0448"']
tensor([[ 0.2447, -0.2277,  0.0797]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[64] loss: 0.905
64 ['"127_S_0393"']
tensor([[ 0.2457, -0.2293,  0.0803]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[65] loss: 0.904
65 ['"007_S_1222"']
tensor([[ 0.2473, -0.2310,  0.0805]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[66] loss: 1.069
66 ['"027_S_1385"']
tensor([[ 0.2482, -0.2328,  0.0814]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[67] loss: 1.383
67 ['"116_S_0382"']
tensor([[ 0.2486, -0.2336,  0.0818]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

tensor([2], device='cuda:0')
[29] loss: 1.122
29 ['"023_S_0963"']
tensor([[ 0.3100, -0.2494,  0.0362]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[30] loss: 1.121
30 ['"012_S_1321"']
tensor([[ 0.3083, -0.2493,  0.0378]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[31] loss: 0.848
31 ['"127_S_0844"']
tensor([[ 0.3074, -0.2494,  0.0388]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[32] loss: 1.406
32 ['"012_S_0689"']
tensor([[ 0.3062, -0.2487,  0.0393]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[33] loss: 1.405
33 ['"130_S_1337"']
tensor([[ 0.3045, -0.2472,  0.0394]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[34] loss: 1.403
34 ['"027_S_0417"']
tensor([[ 0.3026, -0.2450,  0.0391]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[35] loss: 0.853
35 ['"126_S_0606"']
tensor([[ 0.3015, -0.2433,  0.0385]], device='

0 ['"067_S_0607"']
Validation
[1] loss: 0.870


1 ['"128_S_1088"']
Validation
[2] loss: 0.870


2 ['"136_S_0195"']
Validation
[3] loss: 0.870


3 ['"002_S_0413"']
Validation
[4] loss: 1.082


4 ['"067_S_0290"']
Validation
[5] loss: 0.870


5 ['"018_S_0450"']
Validation
[6] loss: 0.870


6 ['"127_S_0260"']
Validation
[7] loss: 1.082


7 ['"116_S_1232"']
Validation
[8] loss: 1.082


8 ['"130_S_0505"']
Validation
[9] loss: 0.870


9 ['"100_S_0190"']
Validation
[10] loss: 0.870


10 ['"023_S_0388"']
Validation
[11] loss: 0.870


11 ['"023_S_0625"']
Validation
[12] loss: 0.870


0 ['"002_S_1070"']
tensor([[ 0.2860, -0.2627,  0.0740]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[1] loss: 0.870
1 ['"051_S_1123"']
tensor([[ 0.2889, -0.2643,  0.0728]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[2] loss: 1.084
2 ['"136_S_0184"']
tensor([[ 0.2910, -0.2661,  0.0724]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0

[52] loss: 1.037
52 ['"051_S_1131"']
tensor([[ 0.2705, -0.2946,  0.1225]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[53] loss: 0.888
53 ['"012_S_1321"']
tensor([[ 0.2705, -0.2946,  0.1225]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[54] loss: 0.888
54 ['"023_S_0031"']
tensor([[ 0.2712, -0.2948,  0.1220]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[55] loss: 1.037
55 ['"016_S_1121"']
tensor([[ 0.2714, -0.2953,  0.1224]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[56] loss: 0.887
56 ['"023_S_0916"']
tensor([[ 0.2722, -0.2960,  0.1223]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[57] loss: 1.455
57 ['"031_S_1209"']
tensor([[ 0.2725, -0.2958,  0.1217]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[58] loss: 1.455
58 ['"023_S_0078"']
tensor([[ 0.2722, -0.2947,  0.1208]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3360, -0.3163,  0.0790]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[20] loss: 1.483
20 ['"037_S_0303"']
tensor([[ 0.3359, -0.3175,  0.0802]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[21] loss: 1.086
21 ['"051_S_1331"']
tensor([[ 0.3354, -0.3188,  0.0821]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[22] loss: 0.831
22 ['"027_S_1081"']
tensor([[ 0.3355, -0.3202,  0.0834]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[23] loss: 1.487
23 ['"005_S_0602"']
tensor([[ 0.3352, -0.3206,  0.0841]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[24] loss: 1.083
24 ['"023_S_0376"']
tensor([[ 0.3343, -0.3212,  0.0856]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[25] loss: 0.832
25 ['"023_S_0855"']
tensor([[ 0.3342, -0.3220,  0.0866]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

[75] loss: 0.841
75 ['"027_S_1385"']
tensor([[ 0.3251, -0.3091,  0.0823]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[76] loss: 1.474
76 ['"002_S_1070"']
tensor([[ 0.3258, -0.3081,  0.0807]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[77] loss: 0.839
77 ['"018_S_0425"']
tensor([[ 0.3270, -0.3075,  0.0788]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[78] loss: 1.086
78 ['"023_S_0078"']
tensor([[ 0.3277, -0.3072,  0.0779]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[79] loss: 0.837
79 ['"130_S_0969"']
tensor([[ 0.3289, -0.3072,  0.0766]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[80] loss: 1.088
80 ['"032_S_0677"']
tensor([[ 0.3295, -0.3075,  0.0763]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[81] loss: 1.088
81 ['"016_S_0769"']
tensor([[ 0.3295, -0.3080,  0.0768]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([0], device='cuda:0')
[43] loss: 0.820
43 ['"012_S_0689"']
tensor([[ 0.3474, -0.3384,  0.0901]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[44] loss: 1.509
44 ['"127_S_0393"']
tensor([[ 0.3445, -0.3376,  0.0922]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[45] loss: 0.825
45 ['"027_S_0417"']
tensor([[ 0.3426, -0.3371,  0.0936]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[46] loss: 0.827
46 ['"053_S_0507"']
tensor([[ 0.3416, -0.3369,  0.0944]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[47] loss: 0.828
47 ['"023_S_0061"']
tensor([[ 0.3413, -0.3370,  0.0948]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[48] loss: 1.075
48 ['"032_S_1101"']
tensor([[ 0.3405, -0.3373,  0.0959]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[49] loss: 1.507
49 ['"027_S_1082"']
tensor([[ 0.3393, -0.3367,  0.0965]], device='

tensor([[ 0.3368, -0.3160,  0.0777]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[11] loss: 0.830
11 ['"023_S_0078"']
tensor([[ 0.3383, -0.3156,  0.0757]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[12] loss: 0.828
12 ['"027_S_1081"']
tensor([[ 0.3403, -0.3154,  0.0735]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[13] loss: 1.482
13 ['"018_S_0633"']
tensor([[ 0.3417, -0.3144,  0.0711]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[14] loss: 1.481
14 ['"005_S_0814"']
tensor([[ 0.3424, -0.3126,  0.0686]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[15] loss: 1.479
15 ['"067_S_1253"']
tensor([[ 0.3424, -0.3101,  0.0659]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[16] loss: 1.476
16 ['"005_S_0602"']
tensor([[ 0.3420, -0.3070,  0.0631]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

tensor([2], device='cuda:0')
[66] loss: 1.098
66 ['"005_S_0448"']
tensor([[ 0.3444, -0.3189,  0.0730]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[67] loss: 0.823
67 ['"037_S_0303"']
tensor([[ 0.3433, -0.3203,  0.0756]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[68] loss: 1.092
68 ['"094_S_1293"']
tensor([[ 0.3417, -0.3219,  0.0788]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[69] loss: 0.826
69 ['"007_S_1206"']
tensor([[ 0.3410, -0.3236,  0.0812]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[70] loss: 1.086
70 ['"018_S_0425"']
tensor([[ 0.3399, -0.3254,  0.0842]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[71] loss: 1.084
71 ['"002_S_0954"']
tensor([[ 0.3383, -0.3273,  0.0877]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[72] loss: 0.830
72 ['"032_S_0677"']
tensor([[ 0.3376, -0.3292,  0.0905]], device='

tensor([0], device='cuda:0')
[50] loss: 0.840
50 ['"027_S_0404"']
tensor([[ 0.3294, -0.3532,  0.1234]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[51] loss: 1.524
51 ['"023_S_1126"']
tensor([[ 0.3279, -0.3524,  0.1242]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[52] loss: 0.842
52 ['"018_S_0369"']
tensor([[ 0.3272, -0.3520,  0.1245]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[53] loss: 1.046
53 ['"126_S_0606"']
tensor([[ 0.3261, -0.3519,  0.1255]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[54] loss: 1.522
54 ['"023_S_0916"']
tensor([[ 0.3246, -0.3509,  0.1260]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[55] loss: 1.521
55 ['"023_S_0604"']
tensor([[ 0.3227, -0.3491,  0.1260]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[56] loss: 0.847
56 ['"100_S_0015"']
tensor([[ 0.3217, -0.3477,  0.1256]], device='

tensor([[ 0.3656, -0.3482,  0.0816]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[18] loss: 1.521
18 ['"027_S_1081"']
tensor([[ 0.3676, -0.3483,  0.0797]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[19] loss: 1.522
19 ['"012_S_0689"']
tensor([[ 0.3689, -0.3475,  0.0775]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[20] loss: 1.521
20 ['"005_S_0814"']
tensor([[ 0.3695, -0.3459,  0.0752]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[21] loss: 1.519
21 ['"128_S_1148"']
tensor([[ 0.3695, -0.3435,  0.0727]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[22] loss: 0.803
22 ['"037_S_0501"']
tensor([[ 0.3702, -0.3416,  0.0700]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[23] loss: 0.803
23 ['"018_S_0369"']
tensor([[ 0.3715, -0.3401,  0.0672]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

tensor([0], device='cuda:0')
[73] loss: 0.808
73 ['"100_S_0015"']
tensor([[ 0.3603, -0.3207,  0.0582]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[74] loss: 1.111
74 ['"037_S_1225"']
tensor([[ 0.3591, -0.3219,  0.0606]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[75] loss: 0.810
75 ['"094_S_1293"']
tensor([[ 0.3587, -0.3232,  0.0623]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[76] loss: 0.811
76 ['"051_S_1123"']
tensor([[ 0.3591, -0.3246,  0.0635]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[77] loss: 1.106
77 ['"023_S_0078"']
tensor([[ 0.3588, -0.3262,  0.0654]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[78] loss: 0.811
78 ['"052_S_1251"']
tensor([[ 0.3593, -0.3278,  0.0667]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[79] loss: 1.103
79 ['"031_S_1209"']
tensor([[ 0.3592, -0.3296,  0.0686]], device='

tensor([[ 0.3525, -0.3260,  0.0716]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[62] loss: 0.817
62 ['"027_S_0403"']
tensor([[ 0.3521, -0.3253,  0.0713]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[63] loss: 1.098
63 ['"116_S_0392"']
tensor([[ 0.3512, -0.3250,  0.0719]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[64] loss: 1.494
64 ['"051_S_1123"']
tensor([[ 0.3499, -0.3238,  0.0719]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[65] loss: 1.096
65 ['"031_S_1209"']
tensor([[ 0.3482, -0.3230,  0.0728]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[66] loss: 1.491
66 ['"130_S_0886"']
tensor([[ 0.3462, -0.3214,  0.0732]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[67] loss: 1.095
67 ['"018_S_0369"']
tensor([[ 0.3438, -0.3202,  0.0743]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

[29] loss: 0.802
29 ['"012_S_0689"']
tensor([[ 0.3767, -0.3646,  0.0875]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[30] loss: 1.541
30 ['"067_S_1253"']
tensor([[ 0.3790, -0.3653,  0.0858]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[31] loss: 1.542
31 ['"082_S_1256"']
tensor([[ 0.3805, -0.3650,  0.0840]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[32] loss: 1.093
32 ['"002_S_1261"']
tensor([[ 0.3813, -0.3650,  0.0831]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[33] loss: 1.094
33 ['"018_S_0406"']
tensor([[ 0.3816, -0.3652,  0.0831]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[34] loss: 0.796
34 ['"002_S_0559"']
tensor([[ 0.3824, -0.3657,  0.0828]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[35] loss: 1.095
35 ['"005_S_0448"']
tensor([[ 0.3826, -0.3663,  0.0832]], device='cuda:0', grad_fn=<ThAddmmBack

0 ['"002_S_0413"']
Validation
[1] loss: 1.069


1 ['"128_S_1088"']
Validation
[2] loss: 0.819


2 ['"100_S_0190"']
Validation
[3] loss: 0.819


3 ['"130_S_0505"']
Validation
[4] loss: 0.819


4 ['"023_S_0388"']
Validation
[5] loss: 0.819


5 ['"018_S_0450"']
Validation
[6] loss: 0.819


6 ['"067_S_0607"']
Validation
[7] loss: 0.819


7 ['"136_S_0195"']
Validation
[8] loss: 0.819


8 ['"127_S_0260"']
Validation
[9] loss: 1.069


9 ['"116_S_1232"']
Validation
[10] loss: 1.069


10 ['"067_S_0290"']
Validation
[11] loss: 0.819


11 ['"023_S_0625"']
Validation
[12] loss: 0.819


0 ['"037_S_0501"']
tensor([[ 0.3544, -0.3598,  0.1049]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[1] loss: 0.819
1 ['"018_S_0633"']
tensor([[ 0.3537, -0.3596,  0.1054]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[2] loss: 1.533
2 ['"130_S_1337"']
tensor([[ 0.3526, -0.3586,  0.1055]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0

[52] loss: 0.824
52 ['"023_S_0604"']
tensor([[ 0.3489, -0.3508,  0.1011]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[53] loss: 0.823
53 ['"023_S_0916"']
tensor([[ 0.3502, -0.3494,  0.0983]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[54] loss: 1.521
54 ['"032_S_0677"']
tensor([[ 0.3508, -0.3472,  0.0954]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[55] loss: 1.076
55 ['"023_S_1247"']
tensor([[ 0.3508, -0.3455,  0.0937]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[56] loss: 0.821
56 ['"005_S_0553"']
tensor([[ 0.3515, -0.3443,  0.0916]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[57] loss: 1.080
57 ['"127_S_0844"']
tensor([[ 0.3516, -0.3434,  0.0906]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[58] loss: 1.514
58 ['"116_S_1249"']
tensor([[ 0.3511, -0.3417,  0.0893]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3631, -0.3686,  0.1053]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[20] loss: 1.544
20 ['"002_S_1261"']
tensor([[ 0.3624, -0.3691,  0.1065]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[21] loss: 1.069
21 ['"032_S_1169"']
tensor([[ 0.3613, -0.3698,  0.1084]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[22] loss: 1.067
22 ['"082_S_1256"']
tensor([[ 0.3598, -0.3708,  0.1109]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[23] loss: 1.065
23 ['"130_S_0449"']
tensor([[ 0.3579, -0.3718,  0.1139]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[24] loss: 0.818
24 ['"136_S_0429"']
tensor([[ 0.3569, -0.3730,  0.1162]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[25] loss: 0.819
25 ['"027_S_0403"']
tensor([[ 0.3566, -0.3744,  0.1179]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

[75] loss: 1.049
75 ['"136_S_0579"']
tensor([[ 0.3533, -0.3802,  0.1272]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[76] loss: 0.823
76 ['"002_S_0559"']
tensor([[ 0.3532, -0.3794,  0.1265]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[77] loss: 1.050
77 ['"127_S_0393"']
tensor([[ 0.3525, -0.3789,  0.1267]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[78] loss: 0.824
78 ['"052_S_1251"']
tensor([[ 0.3526, -0.3787,  0.1264]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[79] loss: 1.050
79 ['"027_S_0404"']
tensor([[ 0.3521, -0.3787,  0.1270]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[80] loss: 1.555
80 ['"130_S_1337"']
tensor([[ 0.3512, -0.3779,  0.1270]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[81] loss: 1.554
81 ['"130_S_0956"']
tensor([[ 0.3498, -0.3762,  0.1267]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3277, -0.3585,  0.1306]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[43] loss: 1.530
43 ['"031_S_1209"']
tensor([[ 0.3262, -0.3587,  0.1323]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[44] loss: 1.530
44 ['"067_S_1253"']
tensor([[ 0.3243, -0.3580,  0.1334]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[45] loss: 1.529
45 ['"021_S_0332"']
tensor([[ 0.3221, -0.3564,  0.1339]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[46] loss: 0.848
46 ['"051_S_1072"']
tensor([[ 0.3209, -0.3552,  0.1340]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[47] loss: 0.849
47 ['"018_S_0406"']
tensor([[ 0.3204, -0.3544,  0.1337]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[48] loss: 0.850
48 ['"023_S_1190"']
tensor([[ 0.3206, -0.3539,  0.1329]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

[10] loss: 1.052
10 ['"023_S_0030"']
tensor([[ 0.3405, -0.3617,  0.1209]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[11] loss: 0.832
11 ['"136_S_0184"']
tensor([[ 0.3408, -0.3618,  0.1207]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[12] loss: 1.052
12 ['"012_S_0689"']
tensor([[ 0.3406, -0.3622,  0.1213]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[13] loss: 1.535
13 ['"012_S_1292"']
tensor([[ 0.3399, -0.3616,  0.1214]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[14] loss: 0.833
14 ['"037_S_1225"']
tensor([[ 0.3399, -0.3613,  0.1211]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[15] loss: 0.833
15 ['"116_S_0487"']
tensor([[ 0.3406, -0.3613,  0.1204]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[16] loss: 1.534
16 ['"116_S_0382"']
tensor([[ 0.3407, -0.3604,  0.1193]], device='cuda:0', grad_fn=<ThAddmmBack

[66] loss: 0.814
66 ['"027_S_0417"']
tensor([[ 0.3685, -0.3867,  0.1186]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[67] loss: 0.810
67 ['"023_S_0061"']
tensor([[ 0.3727, -0.3878,  0.1156]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[68] loss: 1.064
68 ['"136_S_0086"']
tensor([[ 0.3759, -0.3890,  0.1136]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[69] loss: 1.066
69 ['"126_S_0606"']
tensor([[ 0.3782, -0.3903,  0.1126]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[70] loss: 1.571
70 ['"116_S_1249"']
tensor([[ 0.3798, -0.3906,  0.1113]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[71] loss: 1.069
71 ['"130_S_1337"']
tensor([[ 0.3807, -0.3911,  0.1109]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[72] loss: 1.572
72 ['"023_S_1190"']
tensor([[ 0.3810, -0.3906,  0.1102]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3481, -0.3513,  0.1022]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[34] loss: 1.070
34 ['"005_S_0448"']
tensor([[ 0.3475, -0.3511,  0.1026]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[35] loss: 0.824
35 ['"005_S_0324"']
tensor([[ 0.3477, -0.3511,  0.1025]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[36] loss: 0.824
36 ['"023_S_0061"']
tensor([[ 0.3485, -0.3515,  0.1020]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[37] loss: 1.070
37 ['"002_S_0954"']
tensor([[ 0.3487, -0.3520,  0.1024]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[38] loss: 0.823
38 ['"067_S_1253"']
tensor([[ 0.3495, -0.3527,  0.1023]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[39] loss: 1.525
39 ['"023_S_0604"']
tensor([[ 0.3497, -0.3525,  0.1018]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

[1] loss: 1.536
1 ['"032_S_1169"']
tensor([[ 0.3549, -0.3606,  0.1050]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[2] loss: 1.069
2 ['"136_S_0429"']
tensor([[ 0.3540, -0.3599,  0.1052]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[3] loss: 0.820
3 ['"005_S_0553"']
tensor([[ 0.3539, -0.3594,  0.1049]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[4] loss: 1.069
4 ['"007_S_1206"']
tensor([[ 0.3532, -0.3593,  0.1054]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[5] loss: 1.068
5 ['"037_S_0303"']
tensor([[ 0.3521, -0.3594,  0.1067]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[6] loss: 1.067
6 ['"067_S_1253"']
tensor([[ 0.3506, -0.3598,  0.1086]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[7] loss: 1.533
7 ['"031_S_1209"']
tensor([[ 0.3487, -0.3592,  0.1099]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor(

[57] loss: 1.083
57 ['"136_S_1227"']
tensor([[ 0.3559, -0.3471,  0.0900]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[58] loss: 0.816
58 ['"023_S_0078"']
tensor([[ 0.3555, -0.3468,  0.0900]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[59] loss: 0.816
59 ['"052_S_1251"']
tensor([[ 0.3559, -0.3467,  0.0896]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[60] loss: 1.082
60 ['"051_S_1131"']
tensor([[ 0.3557, -0.3469,  0.0900]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[61] loss: 0.816
61 ['"031_S_0830"']
tensor([[ 0.3561, -0.3474,  0.0900]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[62] loss: 0.816
62 ['"002_S_1261"']
tensor([[ 0.3572, -0.3480,  0.0895]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[63] loss: 1.083
63 ['"094_S_1293"']
tensor([[ 0.3577, -0.3488,  0.0899]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([0], device='cuda:0')
[25] loss: 0.819
25 ['"027_S_1277"']
tensor([[ 0.3545, -0.3601,  0.1049]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[26] loss: 0.819
26 ['"031_S_1209"']
tensor([[ 0.3555, -0.3611,  0.1049]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[27] loss: 1.535
27 ['"116_S_0487"']
tensor([[ 0.3559, -0.3610,  0.1044]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[28] loss: 1.535
28 ['"023_S_0963"']
tensor([[ 0.3557, -0.3600,  0.1035]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[29] loss: 1.070
29 ['"130_S_0886"']
tensor([[ 0.3551, -0.3593,  0.1036]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[30] loss: 1.070
30 ['"052_S_1251"']
tensor([[ 0.3539, -0.3590,  0.1044]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[31] loss: 1.069
31 ['"127_S_0622"']
tensor([[ 0.3524, -0.3590,  0.1059]], device='

tensor([2], device='cuda:0')
[81] loss: 1.086
81 ['"128_S_1148"']
tensor([[ 0.3715, -0.3632,  0.0909]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[82] loss: 0.804
82 ['"023_S_0916"']
tensor([[ 0.3711, -0.3637,  0.0919]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[83] loss: 1.539
83 ['"005_S_0602"']
tensor([[ 0.3702, -0.3633,  0.0924]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[84] loss: 1.083
$$Finished Training This Epoch
Start a new val_epoch
0 ['"002_S_0413"']
Validation
[1] loss: 1.082


1 ['"023_S_0625"']
Validation
[2] loss: 0.807


2 ['"127_S_0260"']
Validation
[3] loss: 1.082


3 ['"128_S_1088"']
Validation
[4] loss: 0.807


4 ['"136_S_0195"']
Validation
[5] loss: 0.807


5 ['"067_S_0290"']
Validation
[6] loss: 0.807


6 ['"116_S_1232"']
Validation
[7] loss: 1.082


7 ['"067_S_0607"']
Validation
[8] loss: 0.807


8 ['"018_S_0450"']
Validation
[9] loss: 0.807


9 ['"130_S_0505"']
Valida

tensor([2], device='cuda:0')
[49] loss: 1.115
49 ['"023_S_0061"']
tensor([[ 0.3915, -0.3551,  0.0622]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[50] loss: 1.115
50 ['"023_S_0963"']
tensor([[ 0.3910, -0.3556,  0.0632]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[51] loss: 1.114
51 ['"016_S_0769"']
tensor([[ 0.3900, -0.3563,  0.0649]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[52] loss: 0.787
52 ['"116_S_1249"']
tensor([[ 0.3898, -0.3571,  0.0661]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[53] loss: 1.111
53 ['"052_S_1251"']
tensor([[ 0.3890, -0.3582,  0.0679]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[54] loss: 1.109
54 ['"130_S_1337"']
tensor([[ 0.3878, -0.3593,  0.0704]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[55] loss: 1.536
55 ['"005_S_0324"']
tensor([[ 0.3862, -0.3595,  0.0722]], device='

tensor([[ 0.3693, -0.3743,  0.1047]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[17] loss: 0.808
17 ['"027_S_1277"']
tensor([[ 0.3713, -0.3751,  0.1035]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[18] loss: 0.806
18 ['"136_S_0579"']
tensor([[ 0.3737, -0.3760,  0.1021]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[19] loss: 0.804
19 ['"023_S_0604"']
tensor([[ 0.3766, -0.3771,  0.1003]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[20] loss: 0.802
20 ['"130_S_0956"']
tensor([[ 0.3798, -0.3784,  0.0983]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[21] loss: 1.557
21 ['"007_S_1206"']
tensor([[ 0.3822, -0.3786,  0.0961]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[22] loss: 1.083
22 ['"032_S_1101"']
tensor([[ 0.3838, -0.3790,  0.0949]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[

[72] loss: 0.829
72 ['"082_S_0928"']
tensor([[ 0.3445, -0.3641,  0.1191]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[73] loss: 0.829
73 ['"005_S_0324"']
tensor([[ 0.3456, -0.3635,  0.1174]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[74] loss: 0.828
74 ['"012_S_0689"']
tensor([[ 0.3473, -0.3633,  0.1155]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[75] loss: 1.537
75 ['"067_S_1253"']
tensor([[ 0.3482, -0.3622,  0.1134]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[76] loss: 1.536
76 ['"052_S_1251"']
tensor([[ 0.3486, -0.3603,  0.1110]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[77] loss: 1.062
77 ['"023_S_0061"']
tensor([[ 0.3483, -0.3588,  0.1097]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[78] loss: 1.063
78 ['"002_S_1070"']
tensor([[ 0.3476, -0.3577,  0.1093]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3225, -0.3454,  0.1218]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[40] loss: 1.514
40 ['"127_S_0844"']
tensor([[ 0.3207, -0.3457,  0.1241]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[41] loss: 1.514
41 ['"005_S_0448"']
tensor([[ 0.3185, -0.3451,  0.1256]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[42] loss: 0.850
42 ['"094_S_1293"']
tensor([[ 0.3172, -0.3448,  0.1266]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[43] loss: 0.851
43 ['"051_S_1131"']
tensor([[ 0.3167, -0.3448,  0.1271]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[44] loss: 0.852
44 ['"002_S_0954"']
tensor([[ 0.3169, -0.3450,  0.1271]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[45] loss: 0.851
45 ['"130_S_0449"']
tensor([[ 0.3178, -0.3455,  0.1267]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

[7] loss: 1.062
7 ['"023_S_0855"']
tensor([[ 0.3517, -0.3650,  0.1127]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[8] loss: 0.822
8 ['"007_S_1206"']
tensor([[ 0.3521, -0.3660,  0.1134]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[9] loss: 1.061
9 ['"012_S_1292"']
tensor([[ 0.3519, -0.3671,  0.1147]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[10] loss: 0.822
10 ['"130_S_0969"']
tensor([[ 0.3525, -0.3684,  0.1155]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[11] loss: 1.059
11 ['"128_S_1148"']
tensor([[ 0.3524, -0.3698,  0.1171]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[12] loss: 0.822
12 ['"082_S_0928"']
tensor([[ 0.3530, -0.3713,  0.1180]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[13] loss: 0.822
13 ['"023_S_0061"']
tensor([[ 0.3543, -0.3730,  0.1184]], device='cuda:0', grad_fn=<ThAddmmBackward>)

[63] loss: 1.046
63 ['"023_S_1262"']
tensor([[ 0.3431, -0.3713,  0.1285]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[64] loss: 1.546
64 ['"012_S_1321"']
tensor([[ 0.3426, -0.3703,  0.1279]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[65] loss: 0.832
65 ['"027_S_0835"']
tensor([[ 0.3429, -0.3696,  0.1269]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[66] loss: 0.831
66 ['"067_S_1253"']
tensor([[ 0.3438, -0.3693,  0.1256]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[67] loss: 1.543
67 ['"136_S_0429"']
tensor([[ 0.3442, -0.3681,  0.1240]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[68] loss: 0.830
68 ['"130_S_0449"']
tensor([[ 0.3451, -0.3672,  0.1222]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[69] loss: 0.829
69 ['"005_S_0602"']
tensor([[ 0.3466, -0.3667,  0.1201]], device='cuda:0', grad_fn=<ThAddmmBack

[51] loss: 1.077
51 ['"051_S_1331"']
tensor([[ 0.3612, -0.3605,  0.0991]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[52] loss: 0.813
52 ['"136_S_0184"']
tensor([[ 0.3606, -0.3611,  0.1003]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[53] loss: 1.074
53 ['"053_S_0507"']
tensor([[ 0.3595, -0.3618,  0.1022]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[54] loss: 0.815
54 ['"116_S_0382"']
tensor([[ 0.3592, -0.3628,  0.1034]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[55] loss: 1.071
55 ['"018_S_0406"']
tensor([[ 0.3584, -0.3638,  0.1053]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[56] loss: 0.816
56 ['"116_S_1249"']
tensor([[ 0.3583, -0.3651,  0.1067]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[57] loss: 1.068
57 ['"126_S_0606"']
tensor([[ 0.3578, -0.3664,  0.1086]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3701, -0.3720,  0.1020]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[19] loss: 1.075
19 ['"051_S_1131"']
tensor([[ 0.3713, -0.3736,  0.1024]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[20] loss: 0.806
20 ['"027_S_0403"']
tensor([[ 0.3731, -0.3753,  0.1024]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[21] loss: 1.075
21 ['"027_S_0404"']
tensor([[ 0.3741, -0.3771,  0.1031]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[22] loss: 1.555
22 ['"130_S_0969"']
tensor([[ 0.3745, -0.3778,  0.1034]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[23] loss: 1.075
23 ['"031_S_0830"']
tensor([[ 0.3744, -0.3786,  0.1044]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[24] loss: 0.804
24 ['"130_S_0449"']
tensor([[ 0.3749, -0.3796,  0.1049]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

tensor([0], device='cuda:0')
[74] loss: 0.829
74 ['"023_S_0604"']
tensor([[ 0.3450, -0.3571,  0.1118]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[75] loss: 0.827
75 ['"130_S_0886"']
tensor([[ 0.3467, -0.3565,  0.1095]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[76] loss: 1.063
76 ['"051_S_1072"']
tensor([[ 0.3477, -0.3562,  0.1082]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[77] loss: 0.825
77 ['"136_S_0184"']
tensor([[ 0.3492, -0.3562,  0.1067]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[78] loss: 1.066
78 ['"018_S_0425"']
tensor([[ 0.3501, -0.3564,  0.1061]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[79] loss: 1.067
79 ['"005_S_0814"']
tensor([[ 0.3503, -0.3569,  0.1063]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[80] loss: 1.530
80 ['"128_S_1148"']
tensor([[ 0.3500, -0.3564,  0.1061]], device='

tensor([[ 0.3495, -0.3516,  0.1017]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[42] loss: 0.823
42 ['"005_S_0448"']
tensor([[ 0.3489, -0.3504,  0.1011]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[43] loss: 0.823
43 ['"130_S_0886"']
tensor([[ 0.3490, -0.3495,  0.1001]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[44] loss: 1.072
44 ['"130_S_0956"']
tensor([[ 0.3485, -0.3490,  0.1000]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[45] loss: 1.521
45 ['"002_S_0954"']
tensor([[ 0.3476, -0.3476,  0.0995]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[46] loss: 0.824
46 ['"116_S_0382"']
tensor([[ 0.3475, -0.3466,  0.0986]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[47] loss: 1.073
47 ['"023_S_1190"']
tensor([[ 0.3468, -0.3460,  0.0986]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

[9] loss: 1.055
9 ['"032_S_1101"']
tensor([[ 0.3328, -0.3511,  0.1180]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[10] loss: 1.522
10 ['"094_S_1293"']
tensor([[ 0.3293, -0.3491,  0.1195]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[11] loss: 0.841
11 ['"016_S_1121"']
tensor([[ 0.3268, -0.3476,  0.1204]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[12] loss: 0.843
12 ['"136_S_0579"']
tensor([[ 0.3252, -0.3464,  0.1208]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[13] loss: 0.844
13 ['"023_S_0916"']
tensor([[ 0.3245, -0.3457,  0.1208]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[14] loss: 1.515
14 ['"023_S_0963"']
tensor([[ 0.3233, -0.3441,  0.1203]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[15] loss: 1.049
15 ['"037_S_0501"']
tensor([[ 0.3218, -0.3429,  0.1207]], device='cuda:0', grad_fn=<ThAddmmBackwa

[65] loss: 1.037
65 ['"051_S_1331"']
tensor([[ 0.3135, -0.3472,  0.1333]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[66] loss: 0.855
66 ['"023_S_0376"']
tensor([[ 0.3119, -0.3460,  0.1337]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[67] loss: 0.856
67 ['"082_S_1256"']
tensor([[ 0.3111, -0.3452,  0.1337]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[68] loss: 1.034
68 ['"005_S_0553"']
tensor([[ 0.3099, -0.3447,  0.1344]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[69] loss: 1.034
69 ['"037_S_1225"']
tensor([[ 0.3084, -0.3445,  0.1358]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[70] loss: 0.860
70 ['"027_S_0404"']
tensor([[ 0.3076, -0.3446,  0.1366]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[71] loss: 1.512
71 ['"012_S_1321"']
tensor([[ 0.3065, -0.3438,  0.1369]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3400, -0.3246,  0.0835]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[33] loss: 0.828
33 ['"027_S_1081"']
tensor([[ 0.3404, -0.3236,  0.0821]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[34] loss: 1.491
34 ['"032_S_1101"']
tensor([[ 0.3403, -0.3218,  0.0804]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[35] loss: 1.489
35 ['"053_S_0507"']
tensor([[ 0.3397, -0.3193,  0.0785]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[36] loss: 0.827
36 ['"136_S_0579"']
tensor([[ 0.3398, -0.3173,  0.0764]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[37] loss: 0.827
37 ['"051_S_1072"']
tensor([[ 0.3405, -0.3158,  0.0740]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[38] loss: 0.826
38 ['"032_S_0677"']
tensor([[ 0.3419, -0.3147,  0.0716]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

10 ['"067_S_0290"']
Validation
[11] loss: 0.814


11 ['"100_S_0190"']
Validation
[12] loss: 0.814


0 ['"012_S_0689"']
tensor([[ 0.3614, -0.3654,  0.1037]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[1] loss: 1.541
1 ['"007_S_1222"']
tensor([[ 0.3608, -0.3655,  0.1045]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[2] loss: 1.071
2 ['"052_S_1251"']
tensor([[ 0.3597, -0.3659,  0.1060]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[3] loss: 1.069
3 ['"023_S_0963"']
tensor([[ 0.3582, -0.3665,  0.1081]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[4] loss: 1.067
4 ['"136_S_0429"']
tensor([[ 0.3564, -0.3673,  0.1108]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[5] loss: 0.819
5 ['"018_S_0425"']
tensor([[ 0.3554, -0.3683,  0.1128]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[6] loss: 1.062
6 ['"136_S_0579"']
tenso

[55] loss: 1.066
55 ['"023_S_0078"']
tensor([[ 0.3587, -0.3670,  0.1081]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[56] loss: 0.816
56 ['"037_S_1225"']
tensor([[ 0.3593, -0.3665,  0.1070]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[57] loss: 0.816
57 ['"016_S_0769"']
tensor([[ 0.3605, -0.3663,  0.1056]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[58] loss: 0.815
58 ['"023_S_0376"']
tensor([[ 0.3622, -0.3663,  0.1039]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[59] loss: 0.813
59 ['"031_S_0830"']
tensor([[ 0.3644, -0.3666,  0.1020]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[60] loss: 0.811
60 ['"082_S_0928"']
tensor([[ 0.3671, -0.3671,  0.0998]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[61] loss: 0.809
61 ['"005_S_0602"']
tensor([[ 0.3701, -0.3679,  0.0975]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([2], device='cuda:0')
[23] loss: 1.059
23 ['"032_S_0677"']
tensor([[ 0.3543, -0.3717,  0.1173]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[24] loss: 1.058
24 ['"012_S_0689"']
tensor([[ 0.3539, -0.3731,  0.1191]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[25] loss: 1.549
25 ['"051_S_1123"']
tensor([[ 0.3531, -0.3734,  0.1203]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[26] loss: 1.055
26 ['"023_S_1247"']
tensor([[ 0.3518, -0.3740,  0.1222]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[27] loss: 0.824
27 ['"116_S_0392"']
tensor([[ 0.3513, -0.3747,  0.1234]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[28] loss: 1.550
28 ['"023_S_1046"']
tensor([[ 0.3503, -0.3745,  0.1242]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[29] loss: 0.825
29 ['"012_S_1292"']
tensor([[ 0.3501, -0.3745,  0.1244]], device='

tensor([1], device='cuda:0')
[79] loss: 1.568
79 ['"136_S_1227"']
tensor([[ 0.3549, -0.3879,  0.1333]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[80] loss: 0.823
80 ['"023_S_1262"']
tensor([[ 0.3546, -0.3863,  0.1319]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[81] loss: 1.564
81 ['"031_S_0830"']
tensor([[ 0.3538, -0.3839,  0.1303]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[82] loss: 0.823
82 ['"027_S_0417"']
tensor([[ 0.3537, -0.3819,  0.1284]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[83] loss: 0.823
83 ['"012_S_1009"']
tensor([[ 0.3543, -0.3805,  0.1262]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[84] loss: 1.050
$$Finished Training This Epoch
Start a new val_epoch
0 ['"023_S_0388"']
Validation
[1] loss: 0.822


1 ['"067_S_0290"']
Validation
[2] loss: 0.822


2 ['"127_S_0260"']
Validation
[3] loss: 1.051


3 ['"067_S_0607"'

tensor([[ 0.3495, -0.3513,  0.1012]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[47] loss: 0.823
47 ['"021_S_0332"']
tensor([[ 0.3478, -0.3509,  0.1025]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[48] loss: 0.824
48 ['"067_S_1253"']
tensor([[ 0.3469, -0.3507,  0.1032]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[49] loss: 1.522
49 ['"027_S_1082"']
tensor([[ 0.3456, -0.3497,  0.1035]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[50] loss: 1.521
50 ['"023_S_1262"']
tensor([[ 0.3440, -0.3479,  0.1033]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[51] loss: 1.519
51 ['"023_S_0916"']
tensor([[ 0.3419, -0.3453,  0.1027]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[52] loss: 1.516
52 ['"023_S_0031"']
tensor([[ 0.3396, -0.3421,  0.1018]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

tensor([1], device='cuda:0')
[14] loss: 1.544
14 ['"018_S_0425"']
tensor([[ 0.3565, -0.3682,  0.1115]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[15] loss: 1.064
15 ['"023_S_1262"']
tensor([[ 0.3557, -0.3677,  0.1118]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[16] loss: 1.543
16 ['"037_S_1225"']
tensor([[ 0.3545, -0.3664,  0.1116]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[17] loss: 0.820
17 ['"012_S_1292"']
tensor([[ 0.3541, -0.3654,  0.1110]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[18] loss: 0.820
18 ['"012_S_1009"']
tensor([[ 0.3543, -0.3647,  0.1101]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[19] loss: 1.064
19 ['"023_S_0031"']
tensor([[ 0.3541, -0.3644,  0.1100]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[20] loss: 1.064
20 ['"052_S_1251"']
tensor([[ 0.3533, -0.3644,  0.1107]], device='

tensor([2], device='cuda:0')
[70] loss: 1.059
70 ['"136_S_1227"']
tensor([[ 0.3536, -0.3699,  0.1161]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[71] loss: 0.821
71 ['"023_S_1126"']
tensor([[ 0.3549, -0.3715,  0.1164]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[72] loss: 0.820
72 ['"005_S_0814"']
tensor([[ 0.3568, -0.3732,  0.1162]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[73] loss: 1.549
73 ['"023_S_0916"']
tensor([[ 0.3579, -0.3737,  0.1157]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[74] loss: 1.550
74 ['"023_S_0376"']
tensor([[ 0.3584, -0.3733,  0.1148]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[75] loss: 0.818
75 ['"136_S_0086"']
tensor([[ 0.3595, -0.3732,  0.1136]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[76] loss: 1.062
76 ['"027_S_0417"']
tensor([[ 0.3600, -0.3734,  0.1132]], device='

tensor([[ 0.3642, -0.3680,  0.1035]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[38] loss: 1.072
38 ['"116_S_0382"']
tensor([[ 0.3638, -0.3684,  0.1043]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[39] loss: 1.071
39 ['"136_S_0429"']
tensor([[ 0.3629, -0.3690,  0.1059]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[40] loss: 0.813
40 ['"012_S_0689"']
tensor([[ 0.3628, -0.3699,  0.1068]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[41] loss: 1.546
41 ['"027_S_1082"']
tensor([[ 0.3621, -0.3697,  0.1073]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[42] loss: 1.545
42 ['"023_S_1247"']
tensor([[ 0.3610, -0.3686,  0.1073]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[43] loss: 0.814
43 ['"051_S_1072"']
tensor([[ 0.3607, -0.3679,  0.1069]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

[5] loss: 1.539
5 ['"023_S_0031"']
tensor([[ 0.3542, -0.3617,  0.1071]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[6] loss: 1.067
6 ['"037_S_0501"']
tensor([[ 0.3510, -0.3594,  0.1079]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[7] loss: 0.822
7 ['"027_S_1385"']
tensor([[ 0.3489, -0.3575,  0.1081]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[8] loss: 1.530
8 ['"128_S_1148"']
tensor([[ 0.3465, -0.3550,  0.1080]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[9] loss: 0.826
9 ['"136_S_0086"']
tensor([[ 0.3449, -0.3530,  0.1075]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[10] loss: 1.064
10 ['"032_S_0677"']
tensor([[ 0.3430, -0.3514,  0.1077]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[11] loss: 1.064
11 ['"007_S_1206"']
tensor([[ 0.3408, -0.3502,  0.1088]], device='cuda:0', grad_fn=<ThAddmmBackward>)
ten

[61] loss: 1.041
61 ['"021_S_0332"']
tensor([[ 0.3326, -0.3656,  0.1328]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[62] loss: 0.840
62 ['"037_S_1225"']
tensor([[ 0.3325, -0.3667,  0.1339]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[63] loss: 0.840
63 ['"023_S_0604"']
tensor([[ 0.3332, -0.3678,  0.1345]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[64] loss: 0.840
64 ['"051_S_1072"']
tensor([[ 0.3344, -0.3691,  0.1346]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[65] loss: 0.839
65 ['"027_S_0404"']
tensor([[ 0.3362, -0.3705,  0.1342]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[66] loss: 1.544
66 ['"027_S_1277"']
tensor([[ 0.3372, -0.3709,  0.1335]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[67] loss: 0.836
67 ['"051_S_1331"']
tensor([[ 0.3389, -0.3715,  0.1324]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3188, -0.3590,  0.1399]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[29] loss: 1.031
29 ['"023_S_0916"']
tensor([[ 0.3162, -0.3594,  0.1429]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[30] loss: 1.530
30 ['"067_S_1253"']
tensor([[ 0.3133, -0.3589,  0.1452]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[31] loss: 1.529
31 ['"082_S_0928"']
tensor([[ 0.3103, -0.3574,  0.1468]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[32] loss: 0.860
32 ['"136_S_0184"']
tensor([[ 0.3082, -0.3564,  0.1479]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[33] loss: 1.022
33 ['"136_S_0196"']
tensor([[ 0.3058, -0.3558,  0.1496]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[34] loss: 1.020
34 ['"023_S_0078"']
tensor([[ 0.3032, -0.3554,  0.1519]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

[84] loss: 0.825
$$Finished Training This Epoch
Start a new val_epoch
0 ['"130_S_0505"']
Validation
[1] loss: 0.824


1 ['"136_S_0195"']
Validation
[2] loss: 0.824


2 ['"002_S_0413"']
Validation
[3] loss: 1.054


3 ['"018_S_0450"']
Validation
[4] loss: 0.824


4 ['"023_S_0625"']
Validation
[5] loss: 0.824


5 ['"127_S_0260"']
Validation
[6] loss: 1.054


6 ['"023_S_0388"']
Validation
[7] loss: 0.824


7 ['"067_S_0607"']
Validation
[8] loss: 0.824


8 ['"116_S_1232"']
Validation
[9] loss: 1.054


9 ['"100_S_0190"']
Validation
[10] loss: 0.824


10 ['"128_S_1088"']
Validation
[11] loss: 0.824


11 ['"067_S_0290"']
Validation
[12] loss: 0.824


0 ['"116_S_0487"']
tensor([[ 0.3515, -0.3724,  0.1207]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[1] loss: 1.548
1 ['"005_S_0814"']
tensor([[ 0.3526, -0.3714,  0.1185]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[2] loss: 1.546
2 ['"053_S_0507"']
tensor([[ 0.3531, -0.3695,  0.1161]], 

tensor([0], device='cuda:0')
[52] loss: 0.821
52 ['"116_S_0649"']
tensor([[ 0.3534, -0.3741,  0.1204]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[53] loss: 0.822
53 ['"002_S_1070"']
tensor([[ 0.3529, -0.3742,  0.1210]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[54] loss: 0.823
54 ['"116_S_0382"']
tensor([[ 0.3531, -0.3745,  0.1212]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[55] loss: 1.054
55 ['"051_S_1331"']
tensor([[ 0.3527, -0.3750,  0.1221]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[56] loss: 0.823
56 ['"023_S_1262"']
tensor([[ 0.3531, -0.3758,  0.1225]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[57] loss: 1.551
57 ['"002_S_0954"']
tensor([[ 0.3529, -0.3755,  0.1224]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[58] loss: 0.823
58 ['"116_S_1249"']
tensor([[ 0.3533, -0.3755,  0.1219]], device='

tensor([[ 0.3513, -0.3442,  0.0920]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[20] loss: 0.820
20 ['"023_S_0376"']
tensor([[ 0.3516, -0.3438,  0.0912]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[21] loss: 0.820
21 ['"082_S_0928"']
tensor([[ 0.3526, -0.3436,  0.0900]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[22] loss: 0.819
22 ['"116_S_0392"']
tensor([[ 0.3541, -0.3437,  0.0885]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[23] loss: 1.515
23 ['"023_S_1262"']
tensor([[ 0.3550, -0.3429,  0.0868]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[24] loss: 1.514
24 ['"130_S_1337"']
tensor([[ 0.3553, -0.3412,  0.0849]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[25] loss: 1.513
25 ['"002_S_1261"']
tensor([[ 0.3550, -0.3389,  0.0828]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

[75] loss: 1.067
75 ['"127_S_0844"']
tensor([[ 0.3457, -0.3512,  0.1047]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[76] loss: 1.523
76 ['"018_S_0425"']
tensor([[ 0.3461, -0.3517,  0.1048]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[77] loss: 1.067
77 ['"027_S_0835"']
tensor([[ 0.3459, -0.3524,  0.1057]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[78] loss: 0.826
78 ['"053_S_0507"']
tensor([[ 0.3464, -0.3533,  0.1061]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[79] loss: 0.826
79 ['"116_S_0382"']
tensor([[ 0.3476, -0.3543,  0.1060]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[80] loss: 1.066
80 ['"130_S_0886"']
tensor([[ 0.3481, -0.3555,  0.1067]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[81] loss: 1.066
81 ['"094_S_1293"']
tensor([[ 0.3480, -0.3568,  0.1081]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3927, -0.3828,  0.0898]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[43] loss: 1.564
43 ['"116_S_0382"']
tensor([[ 0.3921, -0.3810,  0.0886]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[44] loss: 1.092
44 ['"027_S_1385"']
tensor([[ 0.3909, -0.3796,  0.0883]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[45] loss: 1.560
45 ['"023_S_1247"']
tensor([[ 0.3894, -0.3775,  0.0877]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[46] loss: 0.790
46 ['"130_S_0956"']
tensor([[ 0.3886, -0.3758,  0.0867]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[47] loss: 1.555
47 ['"027_S_0417"']
tensor([[ 0.3874, -0.3733,  0.0854]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[48] loss: 0.791
48 ['"116_S_1249"']
tensor([[ 0.3869, -0.3713,  0.0838]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

tensor([1], device='cuda:0')
[10] loss: 1.551
10 ['"018_S_0425"']
tensor([[ 0.3601, -0.3739,  0.1134]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[11] loss: 1.063
11 ['"136_S_0579"']
tensor([[ 0.3589, -0.3731,  0.1138]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[12] loss: 0.817
12 ['"116_S_0487"']
tensor([[ 0.3585, -0.3726,  0.1137]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[13] loss: 1.548
13 ['"051_S_1131"']
tensor([[ 0.3576, -0.3713,  0.1132]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[14] loss: 0.818
14 ['"023_S_0963"']
tensor([[ 0.3575, -0.3703,  0.1124]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[15] loss: 1.063
15 ['"007_S_1206"']
tensor([[ 0.3568, -0.3697,  0.1124]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[16] loss: 1.063
16 ['"037_S_0501"']
tensor([[ 0.3557, -0.3694,  0.1132]], device='

tensor([[ 0.3562, -0.3662,  0.1094]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[66] loss: 1.065
66 ['"027_S_0835"']
tensor([[ 0.3565, -0.3659,  0.1088]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[67] loss: 0.818
67 ['"052_S_1251"']
tensor([[ 0.3575, -0.3659,  0.1079]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[68] loss: 1.067
68 ['"018_S_0633"']
tensor([[ 0.3578, -0.3662,  0.1078]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[69] loss: 1.541
69 ['"130_S_1337"']
tensor([[ 0.3576, -0.3655,  0.1073]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[70] loss: 1.540
70 ['"027_S_0404"']
tensor([[ 0.3569, -0.3640,  0.1064]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[71] loss: 1.538
71 ['"012_S_1292"']
tensor([[ 0.3558, -0.3617,  0.1053]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

tensor([2], device='cuda:0')
[33] loss: 1.043
33 ['"082_S_0928"']
tensor([[ 0.3401, -0.3731,  0.1327]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[34] loss: 0.834
34 ['"018_S_0406"']
tensor([[ 0.3399, -0.3735,  0.1332]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[35] loss: 0.834
35 ['"023_S_0604"']
tensor([[ 0.3404, -0.3740,  0.1332]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[36] loss: 0.834
36 ['"130_S_0449"']
tensor([[ 0.3416, -0.3747,  0.1328]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[37] loss: 0.833
37 ['"027_S_0404"']
tensor([[ 0.3433, -0.3756,  0.1320]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[38] loss: 1.550
38 ['"012_S_0689"']
tensor([[ 0.3443, -0.3755,  0.1309]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[39] loss: 1.550
39 ['"127_S_0844"']
tensor([[ 0.3447, -0.3744,  0.1294]], device='


0 ['"016_S_0769"']
tensor([[ 0.3594, -0.3719,  0.1120]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[1] loss: 0.816
1 ['"037_S_0501"']
tensor([[ 0.3603, -0.3721,  0.1113]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[2] loss: 0.815
2 ['"051_S_1072"']
tensor([[ 0.3619, -0.3726,  0.1102]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[3] loss: 0.814
3 ['"005_S_0553"']
tensor([[ 0.3639, -0.3732,  0.1088]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[4] loss: 1.067
4 ['"130_S_0449"']
tensor([[ 0.3652, -0.3740,  0.1084]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[5] loss: 0.811
5 ['"027_S_0404"']
tensor([[ 0.3670, -0.3750,  0.1075]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[6] loss: 1.552
6 ['"032_S_1101"']
tensor([[ 0.3681, -0.3750,  0.1064]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cu

tensor([0], device='cuda:0')
[56] loss: 0.788
56 ['"136_S_0086"']
tensor([[ 0.3950, -0.3942,  0.0991]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[57] loss: 1.084
57 ['"032_S_0677"']
tensor([[ 0.3945, -0.3943,  0.0996]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[58] loss: 1.083
58 ['"018_S_0425"']
tensor([[ 0.3936, -0.3946,  0.1009]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[59] loss: 1.082
59 ['"027_S_1277"']
tensor([[ 0.3922, -0.3951,  0.1028]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[60] loss: 0.790
60 ['"018_S_0369"']
tensor([[ 0.3916, -0.3958,  0.1042]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[61] loss: 1.078
61 ['"005_S_0814"']
tensor([[ 0.3905, -0.3967,  0.1062]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[62] loss: 1.579
62 ['"027_S_0403"']
tensor([[ 0.3890, -0.3966,  0.1075]], device='

tensor([[ 0.3538, -0.3687,  0.1143]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[24] loss: 0.821
24 ['"027_S_1081"']
tensor([[ 0.3544, -0.3687,  0.1138]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[25] loss: 1.543
25 ['"051_S_1123"']
tensor([[ 0.3543, -0.3679,  0.1130]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[26] loss: 1.062
26 ['"053_S_0507"']
tensor([[ 0.3537, -0.3673,  0.1130]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[27] loss: 0.821
27 ['"018_S_0633"']
tensor([[ 0.3539, -0.3671,  0.1126]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[28] loss: 1.542
28 ['"002_S_1261"']
tensor([[ 0.3535, -0.3660,  0.1118]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[29] loss: 1.062
29 ['"136_S_0184"']
tensor([[ 0.3527, -0.3652,  0.1119]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

[79] loss: 0.844
79 ['"094_S_1293"']
tensor([[ 0.3309, -0.3690,  0.1376]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[80] loss: 0.842
80 ['"127_S_0393"']
tensor([[ 0.3337, -0.3690,  0.1348]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[81] loss: 0.839
81 ['"127_S_0844"']
tensor([[ 0.3369, -0.3692,  0.1318]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[82] loss: 1.543
82 ['"051_S_1131"']
tensor([[ 0.3392, -0.3685,  0.1288]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[83] loss: 0.834
83 ['"007_S_1206"']
tensor([[ 0.3420, -0.3682,  0.1256]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[84] loss: 1.048
$$Finished Training This Epoch
Start a new val_epoch
0 ['"128_S_1088"']
Validation
[1] loss: 0.830


1 ['"023_S_0388"']
Validation
[2] loss: 0.830


2 ['"127_S_0260"']
Validation
[3] loss: 1.050


3 ['"067_S_0607"']
Validation
[4] loss: 0.830


tensor([[ 0.3623, -0.3715,  0.1086]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[47] loss: 1.547
47 ['"007_S_1222"']
tensor([[ 0.3623, -0.3699,  0.1069]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[48] loss: 1.069
48 ['"023_S_0604"']
tensor([[ 0.3618, -0.3686,  0.1061]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[49] loss: 0.814
49 ['"053_S_0507"']
tensor([[ 0.3620, -0.3677,  0.1050]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[50] loss: 0.813
50 ['"037_S_1225"']
tensor([[ 0.3629, -0.3671,  0.1035]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[51] loss: 0.812
51 ['"023_S_1126"']
tensor([[ 0.3643, -0.3669,  0.1019]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[52] loss: 0.811
52 ['"018_S_0369"']
tensor([[ 0.3662, -0.3669,  0.0999]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

tensor([0], device='cuda:0')
[14] loss: 0.815
14 ['"037_S_0303"']
tensor([[ 0.3601, -0.3615,  0.1006]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[15] loss: 1.074
15 ['"023_S_0031"']
tensor([[ 0.3600, -0.3621,  0.1013]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[16] loss: 1.073
16 ['"012_S_1292"']
tensor([[ 0.3593, -0.3628,  0.1027]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[17] loss: 0.815
17 ['"005_S_0324"']
tensor([[ 0.3594, -0.3638,  0.1036]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[18] loss: 0.815
18 ['"051_S_1131"']
tensor([[ 0.3601, -0.3649,  0.1039]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[19] loss: 0.815
19 ['"130_S_0449"']
tensor([[ 0.3615, -0.3661,  0.1039]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[20] loss: 0.814
20 ['"051_S_1331"']
tensor([[ 0.3633, -0.3674,  0.1034]], device='

tensor([[ 0.3876, -0.3831,  0.0950]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[70] loss: 0.793
70 ['"116_S_0392"']
tensor([[ 0.3858, -0.3821,  0.0957]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[71] loss: 1.562
71 ['"023_S_1190"']
tensor([[ 0.3836, -0.3802,  0.0960]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[72] loss: 1.083
72 ['"023_S_0078"']
tensor([[ 0.3812, -0.3788,  0.0971]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[73] loss: 0.798
73 ['"127_S_0844"']
tensor([[ 0.3796, -0.3778,  0.0976]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[74] loss: 1.556
74 ['"023_S_0963"']
tensor([[ 0.3776, -0.3760,  0.0977]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[75] loss: 1.080
75 ['"136_S_0579"']
tensor([[ 0.3754, -0.3746,  0.0985]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[

tensor([0], device='cuda:0')
[37] loss: 0.823
37 ['"016_S_1121"']
tensor([[ 0.3559, -0.3852,  0.1289]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[38] loss: 0.821
38 ['"051_S_1072"']
tensor([[ 0.3586, -0.3862,  0.1273]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[39] loss: 0.819
39 ['"005_S_0814"']
tensor([[ 0.3617, -0.3875,  0.1254]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[40] loss: 1.566
40 ['"023_S_0855"']
tensor([[ 0.3639, -0.3876,  0.1233]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[41] loss: 0.814
41 ['"023_S_0376"']
tensor([[ 0.3666, -0.3880,  0.1210]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[42] loss: 0.812
42 ['"130_S_0886"']
tensor([[ 0.3697, -0.3886,  0.1186]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[43] loss: 1.060
43 ['"005_S_0553"']
tensor([[ 0.3719, -0.3894,  0.1171]], device='

[4] loss: 0.817
4 ['"032_S_1101"']
tensor([[ 0.3569, -0.3609,  0.1030]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[5] loss: 1.535
5 ['"130_S_1337"']
tensor([[ 0.3562, -0.3595,  0.1022]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[6] loss: 1.533
6 ['"012_S_1292"']
tensor([[ 0.3551, -0.3573,  0.1011]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[7] loss: 0.818
7 ['"127_S_0622"']
tensor([[ 0.3548, -0.3556,  0.0997]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[8] loss: 1.073
8 ['"023_S_0030"']
tensor([[ 0.3539, -0.3542,  0.0992]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[9] loss: 0.819
9 ['"116_S_1249"']
tensor([[ 0.3538, -0.3533,  0.0983]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[10] loss: 1.074
10 ['"023_S_0604"']
tensor([[ 0.3532, -0.3527,  0.0983]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tenso

[60] loss: 1.067
60 ['"130_S_0969"']
tensor([[ 0.3400, -0.3464,  0.1051]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[61] loss: 1.065
61 ['"136_S_0429"']
tensor([[ 0.3394, -0.3479,  0.1072]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[62] loss: 0.831
62 ['"027_S_1082"']
tensor([[ 0.3395, -0.3495,  0.1087]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[63] loss: 1.520
63 ['"023_S_1247"']
tensor([[ 0.3391, -0.3500,  0.1097]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[64] loss: 0.832
64 ['"023_S_0078"']
tensor([[ 0.3395, -0.3508,  0.1101]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[65] loss: 0.831
65 ['"027_S_0404"']
tensor([[ 0.3404, -0.3517,  0.1101]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[66] loss: 1.523
66 ['"023_S_0031"']
tensor([[ 0.3407, -0.3516,  0.1097]], device='cuda:0', grad_fn=<ThAddmmBack

tensor([[ 0.3224, -0.3263,  0.1023]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[28] loss: 0.844
28 ['"016_S_1121"']
tensor([[ 0.3234, -0.3266,  0.1016]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[29] loss: 0.843
29 ['"018_S_0425"']
tensor([[ 0.3249, -0.3271,  0.1006]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[30] loss: 1.066
30 ['"005_S_0553"']
tensor([[ 0.3258, -0.3279,  0.1004]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[31] loss: 1.066
31 ['"031_S_0830"']
tensor([[ 0.3261, -0.3288,  0.1010]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[32] loss: 0.841
32 ['"027_S_1081"']
tensor([[ 0.3271, -0.3299,  0.1012]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[33] loss: 1.497
33 ['"116_S_1249"']
tensor([[ 0.3274, -0.3299,  0.1009]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[

[83] loss: 0.825
83 ['"037_S_1225"']
tensor([[ 0.3466, -0.3525,  0.1048]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[84] loss: 0.825
$$Finished Training This Epoch
Start a new val_epoch
0 ['"128_S_1088"']
Validation
[1] loss: 0.825


1 ['"023_S_0625"']
Validation
[2] loss: 0.825


2 ['"136_S_0195"']
Validation
[3] loss: 0.825


3 ['"127_S_0260"']
Validation
[4] loss: 1.066


4 ['"067_S_0607"']
Validation
[5] loss: 0.825


5 ['"130_S_0505"']
Validation
[6] loss: 0.825


6 ['"023_S_0388"']
Validation
[7] loss: 0.825


7 ['"067_S_0290"']
Validation
[8] loss: 0.825


8 ['"116_S_1232"']
Validation
[9] loss: 1.066


9 ['"002_S_0413"']
Validation
[10] loss: 1.066


10 ['"018_S_0450"']
Validation
[11] loss: 0.825


11 ['"100_S_0190"']
Validation
[12] loss: 0.825


0 ['"018_S_0425"']
tensor([[ 0.3471, -0.3540,  0.1058]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[1] loss: 1.066
1 ['"023_S_0031"']
tensor([[ 0.3471, -0.3556,  0.1074]]

tensor([2], device='cuda:0')
[51] loss: 1.043
51 ['"126_S_0606"']
tensor([[ 0.3544, -0.3911,  0.1363]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[52] loss: 1.569
52 ['"007_S_1222"']
tensor([[ 0.3532, -0.3910,  0.1375]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[53] loss: 1.040
53 ['"037_S_0501"']
tensor([[ 0.3516, -0.3912,  0.1392]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[54] loss: 0.826
54 ['"127_S_0844"']
tensor([[ 0.3509, -0.3916,  0.1404]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[55] loss: 1.569
55 ['"002_S_0559"']
tensor([[ 0.3496, -0.3910,  0.1411]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[56] loss: 1.036
56 ['"128_S_1148"']
tensor([[ 0.3480, -0.3908,  0.1424]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[57] loss: 0.829
57 ['"021_S_0332"']
tensor([[ 0.3472, -0.3907,  0.1432]], device='

tensor([[ 0.3738, -0.3858,  0.1115]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[19] loss: 0.805
19 ['"012_S_0689"']
tensor([[ 0.3748, -0.3871,  0.1118]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[20] loss: 1.566
20 ['"136_S_0086"']
tensor([[ 0.3752, -0.3873,  0.1116]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[21] loss: 1.068
21 ['"023_S_0916"']
tensor([[ 0.3750, -0.3877,  0.1122]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[22] loss: 1.567
22 ['"032_S_1101"']
tensor([[ 0.3743, -0.3871,  0.1123]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[23] loss: 1.566
23 ['"082_S_1256"']
tensor([[ 0.3732, -0.3857,  0.1120]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[24] loss: 1.067
24 ['"116_S_0487"']
tensor([[ 0.3716, -0.3847,  0.1125]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[

tensor([0], device='cuda:0')
[74] loss: 0.818
74 ['"023_S_0855"']
tensor([[ 0.3538, -0.3540,  0.0990]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[75] loss: 0.819
75 ['"094_S_1293"']
tensor([[ 0.3537, -0.3551,  0.1002]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[76] loss: 0.819
76 ['"051_S_1123"']
tensor([[ 0.3542, -0.3563,  0.1009]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[77] loss: 1.072
77 ['"127_S_0622"']
tensor([[ 0.3542, -0.3576,  0.1023]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([2], device='cuda:0')
[78] loss: 1.071
78 ['"027_S_1082"']
tensor([[ 0.3536, -0.3590,  0.1043]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([1], device='cuda:0')
[79] loss: 1.532
79 ['"130_S_0449"']
tensor([[ 0.3526, -0.3594,  0.1057]], device='cuda:0', grad_fn=<ThAddmmBackward>)
tensor([0], device='cuda:0')
[80] loss: 0.821
80 ['"023_S_0061"']
tensor([[ 0.3524, -0.3600,  0.1065]], device='

In [15]:
import torch
#test after finish all epochs

#load the best_model back 
final_net = torch.load('best_model_2.pkl')
final_net.eval()
correct_sum = 0.
total_sum = 0.
for i_batch, sample_batched in enumerate(dataloader_test):
    print(i_batch,
          sample_batched['patient_id'])

    running_loss = 0.0
    # get the inputs
    labels_arr = np.asarray(sample_batched['groups'])
    labels_arr = labels_arr.astype(np.int)
    labels = ToTensor(labels_arr).cuda()

    images_arr = np.asarray(sample_batched['image'])
    images_arr = images_arr.astype(np.float)
    images_arr = np.expand_dims(images_arr, 1)
    images = ToTensor(images_arr).cuda()

    outputs = final_net(images)#n * 3
    results_type = np.argmax(outputs.cpu().data.numpy(), axis=1)
    results_type = ToTensor(results_type)
    print(outputs)

    #calculate accuracy
    labels = labels.cpu()
    print("\n", results_type, " ", labels)

    
    correct_sum += (labels == results_type)
    total_sum += 1


print("correct_sum_final", correct_sum)
print(total_sum)


0 ['"136_S_0300"']
tensor([[ 0.3503, -0.3610,  0.1096]], device='cuda:0', grad_fn=<ThAddmmBackward>)

 tensor([0.])   tensor([1.])
1 ['"016_S_1117"']
tensor([[ 0.3503, -0.3610,  0.1096]], device='cuda:0', grad_fn=<ThAddmmBackward>)

 tensor([0.])   tensor([0.])
2 ['"002_S_1018"']
tensor([[ 0.3503, -0.3610,  0.1096]], device='cuda:0', grad_fn=<ThAddmmBackward>)

 tensor([0.])   tensor([1.])
3 ['"052_S_1250"']
tensor([[ 0.3503, -0.3610,  0.1096]], device='cuda:0', grad_fn=<ThAddmmBackward>)

 tensor([0.])   tensor([2.])
4 ['"136_S_0426"']
tensor([[ 0.3504, -0.3610,  0.1096]], device='cuda:0', grad_fn=<ThAddmmBackward>)

 tensor([0.])   tensor([1.])
5 ['"005_S_0572"']
tensor([[ 0.3504, -0.3610,  0.1096]], device='cuda:0', grad_fn=<ThAddmmBackward>)

 tensor([0.])   tensor([0.])
6 ['"023_S_0926"']
tensor([[ 0.3503, -0.3610,  0.1096]], device='cuda:0', grad_fn=<ThAddmmBackward>)

 tensor([0.])   tensor([2.])
7 ['"023_S_0139"']
tensor([[ 0.3503, -0.3610,  0.1096]], device='cuda:0', grad_fn=<